### ISSUE TITLE
state option in congressional_district() errors

### ISSUE THREAD

**Issue by kuriwaki** [walkerke/tigris#100]
Despite the new (helpful) argument in the dev version, setting to a state doesn't seem to complete. 

```
> packageVersion("tigris")
[1] ‘1.0.9000’
> congressional_districts(state = "FL", cb = TRUE, year = 2016)
Error in load_tiger(url, tigris_type = "congressional_districts", ...) : 
  unused argument (state = "FL")
```

**Comment by walkerke** [comment]
I just tested this and it works with the latest development version of tigris.  Are you still having this issue?

**Comment by kuriwaki** [comment]
I get correct output now even though the SHA hasn't changed. Not quite sure why, but thank you.
