### ISSUE TITLE
Couldn't find highway ramp (MTFCC code S1630) in Taylor County (217) in Kentucky (21)

### ISSUE THREAD

**Issue by RealCoChenchao** [walkerke/tigris#101]
This is probably not an issue of this package??

**Comment by walkerke** [comment]
Probably not - tigris is simply going to download whatever Census provides and then read that in.  Additionally, if this is a newer highway ramp, it is possible that the TIGER/Line files are not updated; so OpenStreetMap data might be a better bet.
