### ISSUE TITLE
Unable to Download High Resolution SF

### ISSUE THREAD

**Issue by k6adams** [walkerke/tigris#103]
Hello @walkerke,

I am new to R and GiHub, I apologize for not formatting my code correctly.  Feel free to correct me.

I am having an issue similar to one others have had (see #14, #16), but not quite the same. For some reason, I am able to pull the standard resolution counties file, but have not had luck with any of the higher resolution options. And in my use case, the higher resolution, the better. I work on a US government computer, so the firewall might have something to do with it, but I am not sure. 

> library(tigris)
> options(tigris_use_cache = F)
> library(rappdirs)
> 
> county_map_shape_500k <- counties(cb = TRUE, refresh = TRUE)
> county_map_shape_20m <- counties(cb = TRUE, resolution = '20m', refresh = TRUE)
Cannot open layer cb_2019_us_county_20m
Error in CPL_read_ogr(dsn, layer, query, as.character(options), quiet,  : 
  Opening layer failed.
In addition: Warning message:
In unzip(file_loc, exdir = tmp) : error 1 in extracting from zip file
> user_cache_dir()
[1] "C:\\Users\\KEVIN~1.ADA\\AppData\\Local\\Cache"
> list.files("C:\\Users\\KEVIN~1.ADA\\AppData\\Local\\Cache")
character(0)
> tempdir()
[1] "C:\\Users\\KEVIN~1.ADA\\AppData\\Local\\Temp\\RtmpOOuulg"
> list.files("C:\\Users\\KEVIN~1.ADA\\AppData\\Local\\Temp\\Rtmp6d1ou7")
character(0)
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

**Comment by walkerke** [comment]
You code works for me - sometimes the Census website blocks traffic/is down.  Usually the answer to this is "try again later" so I'd encourage you to do that.  If it is a persistent error, it could have something to do with a firewall.

**Comment by k6adams** [comment]
> You code works for me - sometimes the Census website blocks traffic/is down. Usually the answer to this is "try again later" so I'd encourage you to do that. If it is a persistent error, it could have something to do with a firewall.

Uhg, you are right. I just tried again this morning. and It worked fine. Thanks!
