### ISSUE TITLE
Can't open Layer

### ISSUE THREAD

**Issue by samantaraymadhu6** [walkerke/tigris#104]
library(tidyverse)
library(tidycensus)
library(tigris)
library(sf)
library(sp)
`> cov_ky <- places(state = "KY", cb = TRUE)`
Using FIPS code '21' for state 'KY'
Cannot open layer cb_2019_21_place_500k
Error in CPL_read_ogr(dsn, layer, query, as.character(options), quiet,  : 
  Opening layer failed.

**Comment by walkerke** [comment]
The Census website is currently down for system maintenance, so tigris unfortunately won't work until it is back up (unless you are using cached shapefiles).  When the website is back up, I'd anticipate that it will work as expected.

**Comment by walkerke** [comment]
it is back up and working now as expected!  This happens from time to time; I'd recommend using shapefile caching with `options(tigris_use_cache = TRUE)` to build a cache of data you might use in the future and avoid downloading as much as you can.

**Comment by samantaraymadhu6** [comment]
Thanks for helping out!
