### ISSUE TITLE
Error message is showing to file the issue

### ISSUE THREAD

**Issue by paragemini** [walkerke/tigris#105]
Hello,

I have a simple line of code that is attempting to download nationwide data of Race with geometry for 2018, 5 year estimate (ACS)
x <- get_acs(geography = "us", table = "B02001", year = 2017, geometry = T, output = "wide")

It give me this error message

Error in UseMethod("mutate_") :
no applicable method for 'mutate_' applied to an object of class "c('SpatialPolygonsDataFrame', 'SpatialPolygons', 'Spatial')"
In addition: Warning message:
In proj4string(obj) : CRS object has comment, which is lost in output

Also, when using the above line of code for years prior to 2011, following error message generates

Error: nation is not currently available for years prior to 2011. To request this feature,
file an issue at https://github.com/walkerke/tigris.

Please find the attached picture:

![image](https://user-images.githubusercontent.com/13204081/97116832-ea4db500-16cd-11eb-929e-cdea8a7ea24c.png)

**Comment by walkerke** [comment]
A couple things here - the first error message is telling you that the corresponding feature geometry is not available for 2010.  Unfortunately, access to the US boundary starts at 2013 so this isn't something I can fix.  That said - is there a reason you need the geometry when you are requesting data for the whole country?  I did implement this for completeness purposes but I'm unsure of the use case.  

The second error message suggests to me that you are using old package versions.  Your code runs fine for me with updated packages, so I'd suggest re-installing tidycensus and updating its dependencies, and I think you'll be OK.
