### ISSUE TITLE
url broken specifically for tl_2018_06_tract.zip

### ISSUE THREAD

**Issue by dholstius** [walkerke/tigris#107]
This is failing, at least on my machine:

```
tigris::tracts("CA", year = 2018)
```

Sorry to post here, as it doesn't seem to be a `tigris` issue. The following also results in failure, again on my machine:

```
curl -O https://www2.census.gov/geo/tiger/TIGER2018/TRACT/tl_2018_06_tract.zip
```

Oddly, variations on the year, state, and geography are successful:

:x: `TIGER2018/TRACT/tl_2018_06_tract.zip`
:white_check_mark: `TIGER2019/TRACT/tl_2019_06_tract.zip`
:white_check_mark: `TIGER2018/TRACT/tl_2018_01_tract.zip` 
:white_check_mark: `TIGER2018/BG/tl_2018_06_bg.zip `
:white_check_mark: `TIGER2018/TABBLOCK/tl_2018_06_tabblock10.zip`

Does anyone have a good contact at the US Census Bureau? **Or know of a better place to post this issue?** If you can't reproduce, that'd be good to know too.

**Comment by walkerke** [comment]
This is working for me.  Usually when this happens, the solution is often "wait a bit and try again."  I'd also recommend caching your shapefiles if you can with `options(tigris_use_cache = TRUE)` to avoid having to hit the Census website as much as possible, which can have blips like this.
