### ISSUE TITLE
call_geolocator_latlon not working 

### ISSUE THREAD

**Issue by lmkirvan** [walkerke/tigris#109]
Hello! 

I tried this same geo area on the census API web interface and got data back, but the call in tigris returned an NA. 

tigris::call_geolocator_latlon(33.70383, -84.69793)
 
I'm pretty sure this is because the api now uses the 2020 census blocks. 

length(response$result$geographies$`2010 Census Blocks`[[1]]$GEOID) is now NULL and should be 
length(response$result$geographies$`2020 Census Blocks`[[1]]$GEOID)

Happy to do a pull request if that's easier for you.

**Comment by yjpenny** [comment]
Hi, I am encountering the same issue. Is there a workaround that would allow me to do this with the 2010 census?
