### ISSUE TITLE
zctas(cb = TRUE, state = "XX")  downloads full TIGER/Line ZCTA file

### ISSUE THREAD

**Issue by martinlukk** [walkerke/tigris#110]
I tried to load the ZTCA data file for a specific state, Ohio, using the "state" argument for the function `zctas()`, as below.

```
library(tigris); options(tigris_use_cache = TRUE, tigris_class = "sf")
zctas_oh <- zctas(cb = TRUE, year = 2010, state = "OH")
```

The documentation indicates that this is available only for 2010 and 2000 data. Specifying no year at all or adding the `year = 2010` argument downloads the full 520 MB data set (or loads the cached file on subsequent attempts) but using `year = 2000` downloads the correct, state-specific subset.

**Comment by walkerke** [comment]
Thanks for the heads up!  The function now throws an error when this is attempted.
