### ISSUE TITLE
Feature request: Delete zip files after they have been downloaded and unzipped in the cache dir

### ISSUE THREAD

**Issue by mpaulacaldas** [walkerke/tigris#111]
I get the impression that the space requirements on disk are larger than necessary when using a cache. For example, when I download the ZCTAs shapefiles using `zctas(cb = FALSE, year = 2019)`, I end up using 1.3 GB of space -- twice the size of the estimate given in the documentation (500 MB). This is because the cache stores both the zipped files (509 MB) and the unzipped files (813 MB).

Is there a reason why the zip files are kept in the cache? When I try to delete them myself, `zctas()` will download them again the next time I call it, even if I left the unzipped files untouched.

I am making this request without looking into the source code too much, but I have a vested interest in this and would be happy to contribute a PR if you find the feature worthwhile. 

And thank you for the package! It is very useful 😄

**Comment by walkerke** [comment]
Thanks!  Yes I like this idea and I've been mulling over a function that clears the cache as well for a while.  If you'd like to submit a PR, I'd be happy to review it!

**Comment by walkerke** [comment]
I've made one slight modification, which gives users a keyword argument that allows them to set `keep_zipped_shapefile` to `TRUE` (defaults to `FALSE`) if they want the old behavior.  Thank you for your contribution!

**Comment by mpaulacaldas** [comment]
You're welcome and thank you for merging the change!
