### ISSUE TITLE
is tigris-package.R up to date? confused about default year and cache option

### ISSUE THREAD

**Issue by MatthieuStigler** [walkerke/tigris#114]
Hi

Thanks for this nice package! 

I am confused about the main help page loaded by `?tigris`. According to that page:

- default year is 2015
- cache default is TRUE

Is it possible both are now changed? I see in the code: `getOption("tigris_year", 2019)`, and `getOption("tigris_use_cache", FALSE)`. Could you kindly elaborate on that? Thanks!!

**Comment by walkerke** [comment]
yikes... that hasn't been updated in a while.  The whole `tigris-package.R` file needs an update but I've taken care of the issues you mentioned.  Thanks for pointing this out!

**Comment by MatthieuStigler** [comment]
great, thanks!

Also, may I suggest to correspondingly update the documentation for `tigris_cache_dir`... I believe this will only work if `getOption("tigris_use_cache")` is TRUE? If correct, it might be useful to emphasize this in the doc, I changed the cache, but as had not enabled the option, was quite confused! 

Thanks!
