### ISSUE TITLE
Improve error handling when FTP files not available

### ISSUE THREAD

**Issue by mfherman** [walkerke/tigris#117]
Just a reminder to loop back to this when I (we) have time. If the request to get shape files fails, leave the user an error message saying to try again later. Some examples of this failing for tidycensus users recently:

https://github.com/walkerke/tidycensus/issues/370
https://github.com/walkerke/tidycensus/issues/371
https://github.com/walkerke/tidycensus/issues/372

**Comment by walkerke** [comment]
So tigris usually does a decent job of handling this on its own: https://github.com/walkerke/tigris/blob/master/R/helpers.R#L145-L146; however this message doesn't seem to come through on the tidycensus side.  I'll poke around at it; both packages need to go to CRAN soon so it'll be good to resolve this.  Looks like the Census FTP site is acting up more generally...

**Comment by walkerke** [comment]
@mfherman  - I just implemented some error handling for this over on the tidycensus side.
