### ISSUE TITLE
Generalized vs detailed counties seems odd

### ISSUE THREAD

**Issue by zross** [walkerke/tigris#12]
I'm using the `cb` argument to download a generalized and detailed version of a county file. When I look at the object sizes they seem to be about what you'd expect with a bigger object for the detailed layer. BUT.. when I plot them the "generalized" version seems a lot more detailed. Any thoughts about this?

```r
library(tigris)
library(sp)
dtl <- counties(state="Wisconsin", cb=FALSE)
object.size(dtl) #1938576 bytes 
gen <- counties(state="Wisconsin", cb=TRUE)
object.size(gen) #500248 bytes

par(mfrow=c(1,2))
plot(dtl, main="Detailed?")
plot(gen, main="Generalized?")
```

Here is the plot

![capture](https://cloud.githubusercontent.com/assets/1395177/11277175/6452e33c-8eb3-11e5-8cbd-b27e4d80dcaf.JPG)

**Comment by walkerke** [comment]
Yes, agreed.  This is an artefact of how the Census Bureau prepared the cartographic boundary files - and a reason why I changed the parameter `detailed` to `cb` before the CRAN release.  I appreciate you pointing this out, however, as it is something I need to document more.  

On the whole, the regular TIGER/Line files are larger and more detailed than the cartographic boundary files.  For example, let's take Juneau County in Wisconsin, an interior county.  

```r
library(tigris)
library(sp)

wi1 <- counties('WI')

wi2 <- counties('WI', cb = TRUE)

juneau1 <- wi1[wi1$NAME == 'Juneau', ]

juneau2 <- wi2[wi2$NAME == 'Juneau', ]

object.size(juneau1) #53488 bytes

object.size(juneau2) #13216 bytes
```

However, the cartographic boundary files, unlike the TIGER/Line files, are clipped to the shoreline of the US.  In turn, this introduces _additional_ detail along the shoreline.  For example, here's what we get for Door County: 

```r
door1 <- wi1[wi1$NAME == 'Door', ]

door2 <- wi2[wi2$NAME == 'Door', ]

object.size(door1) #13088 bytes

object.size(door2) #24944 bytes
```

As such you've made a really good point here - I'll include some more documentation about this for the next release.

**Comment by zross** [comment]
Makes sense, I appreciate the detailed answer!
