### ISSUE TITLE
Add other U.S. territories to shift_geometry?

### ISSUE THREAD

**Issue by benjaminrobinson** [walkerke/tigris#123]
Good afternoon, Dr. Walker!
Thank you so much for your work on this package and so many others.  Having a function like `shift_geometry` makes a lot of my job so much easier when I want to make a map that includes Hawaii, Alaska, and Puerto Rico in R.  I've also been relatively successful in convincing some of the analysts in my company's GIS shop to switch over to R from Python specifically because the package environment is so robust and your package(s) play a large role in that!

My organization also wants to make maps that include the U.S. territories (i.e. American Samoa, Guam, Northern Mariana Islands, and the U.S. Virgin Islands in addition to Puerto Rico).  Would it be possible to add these territories as an additional feature implementation to `shift_geometry` down the line.  Thank you so much again for this package!  It would be another feather in the cap of R as part of a go-to ecosystem for our GIS analysts doing data science and making maps outside of ArcGIS/QGIS.

Sincerely, Benjamin Robinson.

**Comment by walkerke** [comment]
Ha, I just posted an issue a couple minutes ago reminding myself to consider this!  It is definitely do-able though it'll take a little time to think through the best way to do it (e.g. where to put them?).  If you have any feedback that'd be great!  I'm going to close this issue and post your comment over in the other thread.

**Comment by benjaminrobinson** [comment]
Will do!
