### ISSUE TITLE
by_sp argument in geo_join() function

### ISSUE THREAD

**Issue by gulinan** [walkerke/tigris#124]
Hi,

I was using `geo_join()` function and noticed that there is an input argument named `by_sp` which refers to the column name we will use for the merge from the spatial data frame. This is not a big deal, but I just wanted to suggest that `by_sf` may sound better in the upcoming versions since we are mostly using `sf` library due to that it follows tidyverse principles. Thanks a lot.

**Comment by walkerke** [comment]
Thanks for the note!  `geo_join()` is a deprecated function and that reminds me to deprecate it in the next release.  Users should use `dplyr::*_join()` instead as those functions work quite well on sf object.
