### ISSUE TITLE
Old Alaska FIPS codes being improperly invalidated, cannot be downloaded

### ISSUE THREAD

**Issue by lpiep** [walkerke/tigris#127]
The county-equivalent geography Skagway-Hoonah-Angoon, AK exists in the 2000 TIGER database with FIPS code 02232, and the blocks file exists here: https://www2.census.gov/geo/tiger/TIGER2010/TABBLOCK/2000/tl_2010_02232_tabblock00.zip

However, the `blocks` function fails to download the 2000 blocks file, and throws an incorrect warning that the FIPS code is invalid. 

```
> blocks(state = '02', county = '232', year = 2000)
Error in unzip(file_loc, exdir = tmp) : invalid zip name argument
In addition: Warning message:
'232' is not a valid FIPS code for counties in Alaska
```

I've tracked it down to the internal `validate_county` function, which throws the warning and, when called in `blocks()` as `county<- validate_county(state, county)`, improperly makes the variable `county` NULL. This NULL value for `county` breaks the otherwise valid URL for the shapefile. 

I suppose this is because the `fips_codes` data represents current FIPS codes and Skagway-Hoonah-Angoon Census area has since become Skagway Municipality and Hoonah-Agnoon Census Area. So, requests for older vintages of census data are being validated on a data set that doesn't align with their vintage.

**Comment by walkerke** [comment]
Yeah, there are a couple of those that we've had to chase down.  I'll push a fix when I have a minute.  In the meantime, you can do:

```r
library(tigris)
library(tidyverse)
options(tigris_use_cache = TRUE)

sha_blocks <- blocks("AK", year = 2000) %>%
  filter(COUNTYFP == "232")
```

**Comment by lpiep** [comment]
Thanks walkerke!

**Comment by lpiep** [comment]
@walkerke your workaround worked for me for Alaska. I put together a list of the defunct counties that no longer appear in the 2020 Census Gazetteer. Does it make sense to just add this to the `fips_codes` data frame in the package? I'd be happy to submit a PR to help if so. 

https://gist.github.com/lpiep/caef0e5f7317071fcfd246d6d4705afa

**Comment by walkerke** [comment]
A PR would be great, thanks!

**Comment by walkerke** [comment]
I merged your PR (sorry for the delay) and it's working well.  Thanks again!
