### ISSUE TITLE
Documenting addtional arguments for tiger functions

### ISSUE THREAD

**Issue by lpiep** [walkerke/tigris#133]
I recently found the `progress_bar` argument for tiger functions (which disables the download progress bar) in an older issue, and I realized it's not documented in the function documentation. Looking at the code for the underlying `load_tiger`, function I see some additional arguments that are not documented. 

I'd like to suggest adding the following text to the details section of the documentation for all relevant functions: 

> ## Additional Arguments
> Additional arguments that can be passed in ... are:
> 
> * `class` Desired class of return object: "sf" (the default) or "sp".
> * `progress_bar` If set to FALSE, do not display download progress bar (helpful for R Markdown documents). Defaults to TRUE.
> * `keep_zipped_shapefile` If set to TRUE, do not delete zipped shapefile (stored in temporary directory or TIGRIS_CACHE_DIR depending on the configuration of global option "tigris_use_cache"). Defaults to FALSE.
> * `refresh` Whether to re-download cached shapefiles (TRUE or FALSE) . The default is either FALSE or the value of global option "tigris_refresh" if it is set. Setting this argument will override the behavior set in "tigris_refresh" global option.

The description for the `...` argument can then be shortened to:
> arguments to be passed to internal function `load_tiger`, which is not exported. See Additional Arguments.

LMK thoughts on that text. I'm happy to submit a PR for it if you agree with the idea.

**Comment by walkerke** [comment]
I like this!  I'll need to work through this but it makes a lot of sense.  I'll include in the next release.
