### ISSUE TITLE
Alternative to geo_join() in dplyr  

### ISSUE THREAD

**Issue by UrbanPlanner42** [walkerke/tigris#135]
Hi,

Based on #124 , I tried to use `dplyr::left_join()` as an alternative to join two spatial data frames, but it didn't work
![{17E429DC-8B38-4F4D-B40E-701F2D10006B} png](https://user-images.githubusercontent.com/10283703/151569044-dc117124-8639-4ba9-9fac-e4c37dc3bb54.jpg)

I could keep using `tigris::geo_join() `but worry about being deprecated in the future.

Thank you

**Comment by walkerke** [comment]
I probably won't deprecate `geo_join()` anytime soon.  I would strongly recommend migrating your workflow to __sf__ from __sp__; this is what the developers of the packages recommend, and they are considering __sp__ deprecated for all intents and purposes, see https://twitter.com/edzerpebesma/status/1272928917700165633.
