### ISSUE TITLE
blocks function doesn't work - new county ( 02063, 02066, 02158, 46102)

### ISSUE THREAD

**Issue by kongkong2006** [walkerke/tigris#137]
Thanks for the package! 
We have the following warning messages when year=2020.
Warning message:
'063' is not a valid FIPS code for counties in Alaska 
Warning message:
'066' is not a valid FIPS code for counties in Alaska 
the last two don't have warning messages but the result is 0.

**Comment by walkerke** [comment]
thanks for the note!  I've just fixed this so re-install from GitHub and it should work as expected.

**Comment by kongkong2006** [comment]
Thank you very much Kyle! It works now.
