### ISSUE TITLE
New `erase_water()` function

### ISSUE THREAD

**Issue by walkerke** [walkerke/tigris#138]
Hi @DHLocke - I got the development bug after our email conversation the other day.  I thought __tigris__ might be the better place for a geometry manipulation function that handles water area, so I've put together a new function, `erase_water()`, that is currently in the GitHub master branch.  For a given input dataset (ideally obtained with tigris / tidycensus), `erase_water()` will automatically fetch water area polygons for that area and erase them from the input dataset.  The `area_threshold` parameter can be tuned to erase only a subset of water areas ranked by size, which can speed up the operation quite a bit.  For example: 

```r
library(tigris)
library(sf)

king_tracts <- tracts(state = "WA", county = "King", year = 2020)

# CRS: NAD 1983 / Washington North (State Plane)
king_erased <- king_tracts %>%
  st_transform(32148) %>%
  erase_water(area_threshold = 0.9)

plot(king_erased$geometry)
```

![image](https://user-images.githubusercontent.com/4872833/153219041-dc754f40-e106-4dcd-80e2-2f824066ff05.png)

It also seems to work for the default CB files in tidycensus because it fetches water area for a given location and surrounding areas, minimizing the chances of sliver polygons.  For example:

```r
library(tigris)
library(tidycensus)
options(tigris_use_cache = TRUE)

phi <- get_decennial(
  geography = "tract",
  variables = "P1_001N",
  state = "PA",
  county = "Philadelphia",
  geometry = TRUE,
  year = 2020
) %>%
  st_transform(3424) %>%
  erase_water(area_threshold = 0.9)

plot(phi['value'])
```

![image](https://user-images.githubusercontent.com/4872833/153219516-9b7405d5-a6ab-47bd-b20b-19150364e86b.png)

Would you mind giving it a try and seeing what you think?

**Comment by DHLocke** [comment]
YES. Thank you so much, I look forward to giving this a try but haven't
found time just yet. Thanks for taking the suggestion and really running
with it. This looks phenomenal at first glance.

-Dexter

**Comment by walkerke** [comment]
This is now on CRAN in tigris 1.6!

**Comment by mapc-lberman** [comment]
this is great!   I was able to run it with a Tigris package update (in R-Studio this was 2.0.1 currently).
the sample code needed library(sf), otherwise it threw an error: [could not find function "st_transform"].
question:  what is the area_threshold(0.9) ?  is the lower number (ie 0.5) going to calculate edges of water boders at a higher resolution?
thanks!

**Comment by walkerke** [comment]
@mapc-lberman `area_threshold` refers to the percentile ranking, by area, used to determine which water areas will be erased from your input features.  So if you choose `area_threshold = 0.9`, water features from the surrounding area in the 90th percentile and above ranked by size (so the largest 10 percent) will be removed.

**Comment by mapc-lberman** [comment]
> @mapc-lberman `area_threshold` refers to the percentile ranking, by area, used to determine which water areas will be erased from your input features. So if you choose `area_threshold = 0.9`, water features from the surrounding area in the 90th percentile and above ranked by size (so the largest 10 percent) will be removed.

thanks, much, that makes perfect sense.
