### ISSUE TITLE
tribal_subdivisions_national link is wrong in body of function

### ISSUE THREAD

**Issue by lmkirvan** [walkerke/tigris#139]
I think that the link is wrong in the body of this function.  The second url should include an be AITSN not AITS. I can open a PR if you'd prefer, but might be easier for you just to fix. 

```
    if (year == 2015) {
        url <- "https://www2.census.gov/geo/tiger/TIGER2015/AITSN/tl_2015_us_aitsn.zip"
    }
    else {
        url <- paste0("https://www2.census.gov/geo/tiger/TIGER", 
            as.character(year), "/AITS/tl_", as.character(year), 
            "_us_aitsn.zip")
    }
```

**Comment by walkerke** [comment]
Thanks!  This is fixed now, and I added CB support for tribal subdivisions, tracts, and block groups as well.
