### ISSUE TITLE
Downloading Incorporated Place shapefiles?

### ISSUE THREAD

**Issue by kerencrum** [walkerke/tigris#143]
Hello,

I am interested in downloading the Census Bureau's Incorporated_Place shapefiles for each state which is located in the States' TigerLine Geodatabase. I looked through the tidycensus and tigris package functions in the R documentation,  but I wasn't sure if any of the options specifically download incorporated places shapefiles. Is there a way to download these through tigris?

![image](https://user-images.githubusercontent.com/100436186/160682991-ebfcbf15-74d7-4eff-a427-1b2d5d16d3ca.png)

**Comment by walkerke** [comment]
Incorporated places are included in the shapefile retrieved by `tigris::places()`.  It looks like the GDB includes a separate filtering step that they don't do for their shapefiles used by __tigris__.  If you want incorporated places only, you can filter on the `LSAD` column; Census-Designated places have the code `"57"`, so something like `tigris::places(state = "CA") |> dplyr::filter(LSAD != "57")` would get you what you need.
