### ISSUE TITLE
cannot plot states() or counties() with cb=F or high resolution

### ISSUE THREAD

**Issue by eliftasar** [walkerke/tigris#144]
Hello, 

I am working from R Studio version 4.1.2 on a macbook pro with 16 GB of memory. 

I am able to plot the following: 
```
ggplot(states(cb=TRUE, resolution='20m')) + geom_sf()
ggplot(counties(cb=TRUE, resolution='20m')) + geom_sf()
```

I can also run the following:
```
states(cb=TRUE, resolution='500k')
counties(cb=TRUE, resolution='500k')
states(resolution='500k')
counties(resolution='500k')
```

However, running any of the following results in no plot and my R session crashing: 
```
ggplot(states(cb=TRUE, resolution='500k')) + geom_sf() 
ggplot(counties(cb=TRUE, resolution='500k')) + geom_sf()
ggplot(states(resolution='500k')) + geom_sf()
ggplot(counties(resolution='500k')) + geom_sf()
ggplot(states()) + geom_sf()
ggplot(counties()) + geom_sf()
```

One of my colleagues has no problem running these lines of code on a PC desktop. Another colleague with a mac has the same issue as me. Do you know what might be going on? Thank you very much!

**Comment by walkerke** [comment]
I'm not a Mac user so I can't help much here - this sounds more like a graphics device issue.  You might read up on these threads for tips: 
- https://stackoverflow.com/questions/65800377/rstudio-graphics-device-really-slow-for-spatial-objects-on-mac.  
- https://github.com/r-spatial/sf/issues/1909

**Comment by eliftasar** [comment]
Thanks very much!
