### ISSUE TITLE
Census geographies for 2011 - 2013 

### ISSUE THREAD

**Issue by perryvaca** [walkerke/tigris#145]
Several geographies (at a minimum: county, ZCTA, MSA) return an error for some of the years between 2011-2013.

E.g.
**counties(cb = TRUE, year = "2013")**
works, but
**counties(cb = TRUE, year = "2012")**
does not.

I can provide better a better reprex if desired.
(Thanks for all you do creating and maintaining this package)

**Comment by perryvaca** [comment]
I just tried it without specifying that cb = TRUE, and it appeared to work, so I guess this is actually just an issue of data availability of the simplified geographies from Census. Apologies if so.

**Comment by walkerke** [comment]
Yes, that's correct! Census does not have CB files for 2011 and 2012.
