### ISSUE TITLE
State Legislative Districts in NH missing?

### ISSUE THREAD

**Issue by ReichYang** [walkerke/tigris#148]
Hi, I was trying to pull the map for NH for the SLD lower chamber.
I have been trying to pull different years but they all seem to be missing some SLD.

For example, State House District Sullivan County goes from 1 to 8, but there are 11 SLD in Sullivan County as shown in the wiki and other voting websites.
Is there any version of the map I should use to get a full match shapefile? Thanks in advance.

**Comment by walkerke** [comment]
__tigris__ just reads in the Census Bureau shapefiles, so you'd have to go directly to them.  For what it's worth, the Census Bureau data seem to match the shapefile found on the New Hampshire state government website: https://www.nh.gov/osi/planning/services/gis/political-districts.htm.  If there have been updates (which there may have been), perhaps they haven't yet been implemented as a shapefile.
