### ISSUE TITLE
tigris 2.0

### ISSUE THREAD

**Issue by walkerke** [walkerke/tigris#149]
I'd like to move the package to version 2.0 before the end of 2022.  The API itself is stable as I'm not planning any major changes; tigris is still widely used and seems to be working well.  The major update will be the removal of the following package dependencies:

- sp
- rgdal
- maptools
- rgeos (from Suggests)

As these dependencies will be retired at the end of 2023, getting this done by the end of 2022 will leave plenty of time for the transition.  Tasks to complete to get this done include: 

- [x] Working through the source code to remove any references to these dependencies.  This is mostly in `load_tiger()` but also shows up in some older helper functions.  
- [x] Reviewing the documentation to remove any references to these dependencies (and updating to more modern code if appropriate).  
- [x] Contacting authors of packages that have tigris in Imports or Suggests to let them know of the upcoming change.  Most look to be sf-era packages so we should be OK.  
- [x] __Push goal__: release __pygris__ (tigris, but for Python) by the end of the year as well.  I've got the basic structure in place locally, so I think it could be do-able.

**Comment by mattspence** [comment]
Is there anything I can do to help with *pygris*? I'm more comfortable programming in Python than R, but I'm happy to try getting documentation in order or helping out otherwise.

**Comment by walkerke** [comment]
@mattspence That would be great!  pygris isn't quite ready to be made public but I'll let you know when it is; there will be plenty of opportunities to contribute I'm sure.

**Comment by walkerke** [comment]
@mattspence I released __pygris__ last week: https://walker-data.com/pygris/.  Any contributions are most welcome!
