### ISSUE TITLE
Plot and sp

### ISSUE THREAD

**Issue by zross** [walkerke/tigris#15]
I see that you're importing `sp` but I'm surprised that the following won't work:

```r
library(tigris)
x<-counties(c("RI", "DE"))
plot(x)
#Error in as.double(y) : 
#  cannot coerce type 'S4' to vector of type 'double'
```

Instead it seems you need to explicitly load `sp` to get the sp plotting methods.

```r
library(tigris)
library(sp)
x<-counties(c("RI", "DE"))
plot(x)
```

I think that this could be confusing for relative beginners, perhaps load the sp plotting methods in the package?

**Comment by walkerke** [comment]
Yes, I agree!  I'll take a look at that.

**Comment by walkerke** [comment]
Just pushed it!  I'll probably submit the updates to CRAN as well in the next week or so.

**Comment by zross** [comment]
importFrom(sp,plot)?

**Comment by walkerke** [comment]
Yes, that's correct: https://github.com/walkerke/tigris/commit/ee8e5a3642fb4bf0dc489a4eccc1119a677161a7
