### ISSUE TITLE
Problems about states() function

### ISSUE THREAD

**Issue by Chuan1997** [walkerke/tigris#156]
Any idea what happened with the function? or MY R?
`> st <- states() `
```
Retrieving data for the year 2021
  |======================================================================================================================| 100%
Error: Cannot open "C:\Users\YWC\AppData\Local\Temp\RtmpAbQimS"; The source could be corrupt or not supported. See `st_drivers()` for a list of supported formats.
In addition: Warning message:
In unzip(file_loc, exdir = tmp) : error 1 in extracting from zip file
```

**Comment by walkerke** [comment]
The function should be working fine; usually that means you have a corrupted data download.  Try running again with `st <- states(refresh = TRUE)` to refresh the download in a new R session and see if that works.

**Comment by Chuan1997** [comment]
Thanks for the suggestion, turns out I need to put `options(tigris_use_cache = TRUE)` in the beginning of the file, and the error is gone!

**Comment by Chuan1997** [comment]
now the new question is states() function returns Download Failed all the time, any possible solutions?
```
Retrieving data for the year 2021
Previous download failed.  Re-download attempt 1 of 3...
  |==============================================================================================| 100%
Previous download failed.  Re-download attempt 2 of 3...
  |==============================================================================================| 100%
Previous download failed.  Re-download attempt 3 of 3...
  |==============================================================================================| 100%
Error: Download failed; check your internet connection or the status of the Census Bureau website
                 at http://www2.census.gov/geo/tiger/.
```
By the way http://www2.census.gov/geo/tiger/ shows Access Denied.

**Comment by walkerke** [comment]
Are you located outside the United States?  Access to US government websites is blocked from some countries.  Given that you can't access http://www2.census.gov/geo/tiger/, you probably won't be able to use the __tigris__ package as it pulls data from there.
