### ISSUE TITLE
Feature request: Lookup table for Census regions and divisions

### ISSUE THREAD

**Issue by 18kimn** [walkerke/tigris#157]
Thanks for the great package :)

I often have to reference which Census region and division each US state belongs to, and usually resort to manually writing them into a CSV via a resource like this one https://www.census.gov/geographies/reference-maps/2010/geo/2010-census-regions-and-divisions-of-the-united-states.html 

I think it would be useful for `tigris` to include this sort of crosswalk between state FIPS codes and Census regions+divisions. This could be a new table entirely, which would ensure non-breakage, or it could be tacked on as two additional columns (`region` and `division`) to the `fips_codes` dataset that tigris currently ships with.

As this is a super small addition I'm happy to create a PR for it

**Comment by lpiep** [comment]
These data sets are actually built into R as part of the standard `datasets` package, believe it or not. 

So you could get what you want without `tigris`, just: 

```
> data.frame(state.name, state.division, state.region)
       state.name     state.division  state.region
1         Alabama East South Central         South
2          Alaska            Pacific          West
3         Arizona           Mountain          West
4        Arkansas West South Central         South
5      California            Pacific          West
6        Colorado           Mountain          West
7     Connecticut        New England     Northeast
8        Delaware     South Atlantic         South
...
```
