### ISSUE TITLE
places() documentation is mistaken?

### ISSUE THREAD

**Issue by ktomari** [walkerke/tigris#161]
## Issue

My apologies if I am not following the correct protocol. I am first time issues poster. This post is with reference to tigris 2.0.1.

I have been trying to figure out how to access incorporated places and I think the documentation for `tigris::places` is incorrect. The documentation title reads: "Download a Census-designated places shapefile into R;" and the description reads: "Census Designated Places (CDPs) are the statistical counterparts of incorporated places, and are delineated to provide data for settled concentrations of population that are identifiable by name but are not legally incorporated under the laws of the state in which they are located." (See https://www.rdocumentation.org/packages/tigris/versions/2.0.1/topics/places)

The `tigris::places` documentation suggests that it downloads CDPs only, but when I run `places` it seems to also download incorporated places. I am stating this based on the values returned for the column MTFCC (MAF/TIGER Feature Class Code) as both G4210 (CDPs) and G4110 (incorporated places) based on the Tiger Technical Manual 2019 (p. 3-56).

## Possible Correction

A possible correction might read:

**Title:** "Download Shapefiles which include both incorporated places (legal entities) and census designated places (statistical entities) into R."

**Description:** "An incorporated place provides governmental functions for a concentration of people. Incorporated places may extend across county and county subdivision boundaries, but never across state boundaries. An incorporated place usually is a city, town, village, or borough, but can have other legal descriptions.

CDPs are the statistical counterparts of incorporated places. CDPs are settled concentrations of population that are identifiable by name but not legally incorporated under the laws of the state in which the CDPs are located.

For more information, read appropriate section on "Places" for the correct vintage (year) of your data in the TIGER/Line Shapefiles and TIGER/Line Files Technical Documentation available as of this writing here: https://www.census.gov/programs-surveys/geography/technical-documentation/complete-technical-documentation/tiger-geo-line.html"

**Comment by walkerke** [comment]
Yes, I think you are right.  I'll make those suggested modifications.
