### ISSUE TITLE
Change border width of some denominations but not others?

### ISSUE THREAD

**Issue by ian-curtis** [walkerke/tigris#162]
Apologies if this doesn't constitute as an "issue". I am working a project with zipcode data and I have thus used the `zctas()` function. I have some wonderful looking maps (so thank you very much for this package) but it's difficult to see where the state boundaries are.

Is there a way to make the state boundaries black while keeping the zipcode boundaries their original color? Perhaps this is more of an R/ggplot thing than a tigris thing so please let me know if I should consult another resource.

Thank you!

**Comment by walkerke** [comment]
Is this what you have in mind?

``` r
library(tigris)
#> To enable caching of data, set `options(tigris_use_cache = TRUE)`
#> in your R script or .Rprofile.
library(tidyverse)
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0; sf_use_s2() is TRUE
options(tigris_use_cache = TRUE)

my_states <- states(cb = TRUE, year = 2020) %>%
  filter(NAME %in% c("Arizona", "Nevada", "California"))

my_zips <- zctas(cb = TRUE, year = 2020, filter_by = summarize(my_states))

ggplot() + 
  geom_sf(data = my_zips, fill = NA, color = "blue") + 
  geom_sf(data = my_states, fill = NA, color = "black",
          linewidth = 1) + 
  theme_void()
```

![](https://i.imgur.com/CnANqfd.png)

<sup>Created on 2023-02-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
