### ISSUE TITLE
zctas(cb = TRUE) pulling down an empty zip file

### ISSUE THREAD

**Issue by edwardbrown** [walkerke/tigris#165]
Greetings. I'm getting an empty zip file when using zctas(cb = TRUE) and I suspect this may have something to do with the census website? Using zctas(cb = FALSE) works fine. 

I've gotten this error when trying to download zctas for 2022, am not sure if 2021 is still default but I got the same empty zip when trying to get 2021 as well.

Thought I would bring it to your attention in case anyone else is having the same problem. Am attaching an example of the zip file that is returned. 

[cb_2022_us_zcta520_500k.zip](https://github.com/walkerke/tigris/files/11116058/cb_2022_us_zcta520_500k.zip)

**Comment by walkerke** [comment]
Thanks for the note - I need to put in some error handling.  Census has not released the 2022 CB files yet; based on last year's schedule, I'd suspect we get them sometime this month.  They also haven't released the CB ZCTA file for 2021, so you'll need to use `year = 2020` for now.

**Comment by edwardbrown** [comment]
Thank you, Kyle. Much appreciated!EdOn Apr 1, 2023, at 15:21, Kyle Walker ***@***.***> wrote:﻿
Thanks for the note - I need to put in some error handling.  Census has not released the 2022 CB files yet; based on last year's schedule, I'd suspect we get them sometime this month.  They also haven't released the CB ZCTA file for 2021, so you'll need to use year = 2020 for now.
