### ISSUE TITLE
Reverse Geocoding zipcode geometries

### ISSUE THREAD

**Issue by LUKE2019-ENG** [walkerke/tigris#168]
Hello,
Is it possible to Geocode/Reverse Geocode the zipcode geometries on Tigris?

**Comment by walkerke** [comment]
tigris doesn't do that, but the zipcodeR package (https://github.com/gavinrozzi/zipcodeR) may meet your needs.

**Comment by LUKE2019-ENG** [comment]
Thanks for the response.
