### ISSUE TITLE
Tract retrieval errors on some states rather than others

### ISSUE THREAD

**Issue by darrellcarvalho** [walkerke/tigris#177]
When utilizing code in "Analyzing Census Data" Chapter 5, following code retrieves error on my end:

`
la_tracts <- tracts("NM", "Los Alamos")
`
> Warning: error 1 in extracting from zip file Cannot open layer tl_2021_35_tract

the error persists at state-level designation
`
tracts("NM")
`
This persists across cached and uncached environments, with refresh set to TRUE and to FALSE.

It does not occur for all (or even most) States, and at time of testing, the Census FTP site is up and the ZIPs are individually accessible.

**Comment by walkerke** [comment]
Strange, I can't reproduce this error.  Sometimes the TIGER website has problems; perhaps try again a bit later and see if it works OK?

**Comment by darrellcarvalho** [comment]
Re-ran in same environment as yesterday, no modifications; after successfully pulling down the two states that failed yesterday, I also pulled down tracts for all states via
```
for (i in state.abb) {
    tigris::tracts(i)
}
```
All function calls were successful, which does seem to point to an issue with the FTP servers sending down the data for a handful of states yesterday.
