### ISSUE TITLE
School District FIPS Codes with leading zeros

### ISSUE THREAD

**Issue by dprinci1** [walkerke/tigris#181]
It seems as though when trying to download district shapefiles with state names, errors are generated for those states with FIPS codes that have a leading zero. 

For example: 
If I try to run this code when Alabama is selected:
districts <- school_districts(input$State)

I get the error:
Retrieving data for the year 2021
Using FIPS code '01' for state 'Alabama'
Warning: Error in sum: invalid 'type' (list) of argument
  109: expandLimits
  108: expandLimitsBbox
  106: addPolygons
  105: getMapData
   99: addLegend
   98: %>%
   97: ::

I don't get errors for any states where the FIPS code doesn't have the leading 0.

**Comment by walkerke** [comment]
The code `school_districts("Alabama")` runs fine for me.  I'm wondering if there is something going on inside your Shiny app?

**Comment by dprinci1** [comment]
You're right, it was an error in my app. Sorry to trouble you, and thanks for your work on tigris, I will be using it a lot! :)
