### ISSUE TITLE
Necessity of curl (through httr)?

### ISSUE THREAD

**Issue by atkissoncj** [walkerke/tigris#187]
I am working on a mapping application that I hope to deliver to local computation through WebR (R in web assembly). The curl package is not supported because of how its use of sockets breaks in js code. Is the curl dependency strictly necessary to deliver tigris? If it's not, what would be required to write it out of the package?

**Comment by walkerke** [comment]
It would require a full refactor of the package, unfortunately.  For your app, my recommendation would be to use tigris to download your files, then save them to a server somewhere / your local filesystem which you can mount.  

This tends to be my recommendation when using tigris in Shiny apps more broadly as the Census FTP server can have hiccups.

**Comment by atkissoncj** [comment]
Great. Thanks, Kyle!

Curtis Atkisson
