### ISSUE TITLE
`year = ` argument not working for blocks()

### ISSUE THREAD

**Issue by tiernanmartin** [walkerke/tigris#20]
It seems that the only `year` arguments that succeed in the `blocks()` function are `2014` and `2015`.

```
> wa_blk <- tigris::blocks(state = 53,county = 33,year = 2012) 
Downloading: 140 kB     
error 1 in extracting from zip fileError in ogrInfo(dsn = dsn, layer = layer, encoding = encoding, use_iconv = use_iconv,  : 
  Cannot open layer
```

**Comment by walkerke** [comment]
I can reproduce the error- I'll take a look at this.

**Comment by walkerke** [comment]
Fixed in https://github.com/walkerke/tigris/commit/54339f845274df702be209a08461d32ceffec36a.
