### ISSUE TITLE
Support for simple features/sf

### ISSUE THREAD

**Issue by walkerke** [walkerke/tigris#22]
The __sf__ package (https://cran.rstudio.com/web/packages/sf/) is now on CRAN; consider adding support for this in __tigris__.  Certainly users could just convert `Spatial*DataFrames` to `sf` objects, but __tigris__ could also read in the Census shapefiles this way directly.

**Comment by walkerke** [comment]
Working on this in https://github.com/walkerke/tigris/tree/sf.  Leads to much faster load times!  I still need to revamp `rbind_tigris` for simple features and make sure the package will build on travis.

**Comment by walkerke** [comment]
Merged in https://github.com/walkerke/tigris/commit/8134c438dd03e36069608abb0788835b968dff4e; still need to think through whether the dplyr strategy for `geo_join` should be re-worked.

**Comment by edzer** [comment]
Regarding `geo_join`: for `sf` objects, it looks like you could simply use `left_join` and `inner_join` from `sf`, up to the `tigris` attributes you want to propagate.
