### ISSUE TITLE
Tutorial site broken

### ISSUE THREAD

**Issue by BrashEQLibrium** [walkerke/tigris#26]
I get a big frowny face when I try to read the tutorial as directed on the R Project site for this package:

http://rpubs.com/walkerke/tigris01

**Comment by keberwein** [comment]
No RPubs pages are rendering for me right now. Probably related to the S3 outage.

**Comment by walkerke** [comment]
While you are waiting, you can read my article in The R Journal on the package: https://journal.r-project.org/archive/2016-2/walker.pdf

**Comment by BrashEQLibrium** [comment]
Was it the S3 outage or were you in the process of updating the package? I remember tidyquant got an update lately (and that the update kicks major ass)

**Comment by walkerke** [comment]
That was the S3 outage - I haven't updated the package since I pushed sf support to GitHub.
