### ISSUE TITLE
Block Data query errror

### ISSUE THREAD

**Issue by dslichtenberg** [walkerke/tigris#27]
Hey All :  big fan of the tigris package but having trouble with block data for certain states:

> tigris::blocks( state= '06', county = '099',  year = 2015)

immediately results in : 
Error in ogrInfo(dsn = dsn, layer = layer, encoding = encoding, use_iconv = use_iconv,  : 
  Cannot open layer
In addition: Warning message:
In unzip(file_loc, exdir = cache_dir, overwrite = TRUE) :
  error 1 in extracting from zip file

many other state and county blocks queries return data as expected.  any ideas ?

i am using R version 3.3.1 (2016-06-21) and tigris_0.3.9.9000

**Comment by walkerke** [comment]
I think the Census website was down this afternoon; it is back up now so try again.  However you'll need to make one modification to correct for the unsuccessful download: add the `refresh = TRUE` argument.  So: 

```
x <- blocks(state = '06', county = '099', refresh = TRUE)
```

should work.
