### ISSUE TITLE
[ENHANCEMENT] Caching

### ISSUE THREAD

**Issue by hrbrmstr** [walkerke/tigris#3]
I haven't pushed it to my fork yet, but I'm thinking that we control the caching & refresh with two `options`:

- `options(tigris_refresh=FALSE)`
- `options(tigris_use_cashe=TRUE)`

users can set these right after they load the package but these wld be the `.onLoad` defaults. 

If that's cool, I'll try to push the PR tonight/tomorrow.

**Comment by walkerke** [comment]
Great stuff.
