### ISSUE TITLE
Unable to download a couple lower house state legistative districts

### ISSUE THREAD

**Issue by undecidedfellow** [walkerke/tigris#30]
I can't seem to download from AL, AK and TX. They all share the following error. I've tried both CRAN version: 0.3.3 and Dev version: 0.3.9.9000.
```
> library(tigris)
> state_legislative_districts("TX", house = 'lower')
Using FIPS code '48' for state 'TX'
Error in ogrInfo(dsn = dsn, layer = layer, encoding = encoding, use_iconv = use_iconv,  : 
  Cannot open layer
In addition: Warning message:
In unzip(file_loc, exdir = cache_dir, overwrite = TRUE) :
  error 1 in extracting from zip file
```

**Comment by walkerke** [comment]
Try adding `refresh = TRUE` to your function call.  You're likely getting the error because of an internet connection hiccup to the Census Bureau website at some point; this should fix it.

**Comment by undecidedfellow** [comment]
That fixed it. Thank you!
