### ISSUE TITLE
Error in ogrInfo: Cannot open layer due to corrupted cache?

### ISSUE THREAD

**Issue by RoyalTS** [walkerke/tigris#31]
Possibly related to/dupe of #16:

I ran

    tigris::tracts(state='CA')

then aborted the download before it could complete. Upon re-executing the command I got

    > tigris::tracts(state='CA')
    Using FIPS code '06' for state 'CA'
    Error in ogrInfo(dsn = dsn, layer = layer, encoding = encoding, use_iconv = use_iconv,  : 
      Cannot open layer
    In addition: Warning message:
    In unzip(file_loc, exdir = cache_dir, overwrite = TRUE) :
      error 1 in extracting from zip file

I'm assuming this is because it's trying to unzip the partially downloaded zip from the first try instead of downloading the zip anew? Forcing a re-download using `refresh=TRUE` as suggested in #16 fixes things. But perhaps `tigris` should be smarter about recognizing such corrupted files?

**Comment by walkerke** [comment]
This is a good idea and shouldn't be too difficult to implement.  I'm pushing a major update to tigris next week or so, I'll look into including this as well.

**Comment by RoyalTS** [comment]
Yeah, I just looked at the code in question and it does seem relatively straightforward. Let me know if you want any help!

**Comment by walkerke** [comment]
I've included this functionality in https://github.com/walkerke/tigris/commit/63fda464e012f3195bd88fc474085c5025c0fb6c and tested - it is working well for me.  Feel free to give it a try!
