### ISSUE TITLE
"insets" option?

### ISSUE THREAD

**Issue by arilamstein** [walkerke/tigris#33]
When rendering maps of the 50 states it is common to render AK and HI as insets, rather than in their "real" place. I searched but did not see an option to get maps from the tigris package in this way. Can you please confirm whether or not this is an option or not?

If it's not an option, can you please let me know whether it's on your roadmap? 

Thanks for the great package.

**Comment by walkerke** [comment]
It's not an option at the moment.  I might consider it in the future, but @hrbrmstr has also solved this with this **albersusa** package: https://github.com/hrbrmstr/albersusa

**Comment by walkerke** [comment]
Given the existence of the __albersusa__ package I'm closing this for now.  I'll re-open if I decide to revisit this in the future.
