### ISSUE TITLE
URL not constructing properly for PUMA files

### ISSUE THREAD

**Issue by gregmacfarlane** [walkerke/tigris#35]
Using 0.5.1 on macOS, R 3.4:

```r
gapuma <-  pumas("Georgia")
## Using FIPS code '13' for state 'Georgia'
## trying URL 'http://www2.census.gov/geo/tiger/TIGER%s/PUMA/tl_%s_%s_puma10.zip2015201513'
## Error in download.file(url, tiger_file, mode = "wb") : 
##   cannot open URL 'http://www2.census.gov/geo/tiger/TIGER%s/PUMA/tl_%s_%s_puma10.zip2015201513'
## In addition: Warning message:
##   In download.file(url, tiger_file, mode = "wb") :
##   cannot open URL 'https://www2.census.gov/geo/tiger/TIGER%s/PUMA/tl_%s_%s_puma10.zip2015201513': HTTP status was '400 Bad Request'
```

Traveling to the URL confirms that the page isn't there. I did find the file I needed at <https://www2.census.gov/geo/tiger/TIGER2012/PUMA/tl_2012_13_puma10.zip>. It seems as though the url constructor isn't building the string correctly.

It works, however, if I turn `cb = TRUE`

**Comment by walkerke** [comment]
Thanks for catching that!  I'll push the fix to GitHub this afternoon.

**Comment by walkerke** [comment]
This is now fixed in https://github.com/walkerke/tigris/commit/a9c6ce62f695ba0c18f6431778f4d76cfa19f2b5.  I'm sending the updates to CRAN today.

**Comment by walkerke** [comment]
FYI: these updates are now in the CRAN version.
