### ISSUE TITLE
[ENHANCEMENT] adding `tigris` attribute to Spatial* objects

### ISSUE THREAD

**Issue by hrbrmstr** [walkerke/tigris#4]
one more for the potential PR. Adding a `tigris` `attr` that will contain the type TIGER object being returned by the various `tigris` functions. That way, we can make an `rbind_tigris` function that will let folks retrieve, say, all the area water shapefiles for a state then rbind them together, auto-creating unique IDs per county. It'll also help for (perhaps) plotting and summary functions.

**Comment by walkerke** [comment]
You've prepared a nice template for the TIGER types with this, and rbind_tigris is excellent.
