### ISSUE TITLE
add curl to the package dependency

### ISSUE THREAD

**Issue by chendaniely** [walkerke/tigris#40]
we (@bi-sdal ) had a huge issue with downloading data in `tigris`.
Mainly because files were not being downloaded properly.
A few things we had to to do to get the tigris working (we tested the package with `va <- states('51')`)

1. must set `options(tigris_use_cache = TRUE)`, otherwise we get the following error:
```r
> va <- states('51')
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Error in ogrInfo(dsn = dsn, layer = layer, encoding = encoding, use_iconv = use_iconv,  : 
  Cannot open data source
In addition: Warning message:
In unzip(tiger_file, exdir = tmp) : error 1 in extracting from zip file
```
2. `install.packages(c("curl", "httr"))`
    - we tried to install the github version of the package, but was running in to SSL CA cert problems (see https://github.com/hadley/devtools/issues/1079)
   - if we do not install these 2 packages we get the following error:
```r
> options(tigris_use_cache = TRUE)
> va <- states('51')              
Previous download failed.  Re-download attempt 1 of 3...
Previous download failed.  Re-download attempt 2 of 3...
Previous download failed.  Re-download attempt 3 of 3...
Error: Download failed; check your internet connection or the status of the Census Bureau website
                 at http://www2.census.gov/geo/tiger/.
```

Here's the `sessionInfo()` without installing `curl` and `httr`

```r
> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS: /usr/lib64/microsoft-r/3.4/lib64/R/lib/libRblas.so
LAPACK: /usr/lib64/microsoft-r/3.4/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] tigris_0.5.3         RevoUtilsMath_10.0.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.12     bindr_0.1        magrittr_1.5     maptools_0.9-2  
 [5] units_0.4-5      rappdirs_0.3.1   uuid_0.1-2       lattice_0.20-35 
 [9] R6_2.2.0         rlang_0.1.1      stringr_1.2.0    udunits2_0.13   
[13] httr_1.2.1       dplyr_0.7.1      tools_3.4.0      rgdal_1.2-8     
[17] grid_3.4.0       DBI_0.7          rgeos_0.3-23     assertthat_0.2.0
[21] tibble_1.3.3     sf_0.5-2         bindrcpp_0.2     curl_2.6        
[25] glue_1.1.1       sp_1.2-5         stringi_1.1.5    compiler_3.4.0  
[29] RevoUtils_10.0.4 foreign_0.8-67   pkgconfig_2.0.1 
```

cc: @dads2busy

**Comment by walkerke** [comment]
Thanks for filing the issue.  I wonder if this has something to do with your Microsoft R installation as I've never heard of this issue before, and it is having trouble downloading files using both methods.  

I'll do a couple things: 

1. Add __curl__ to the package dependencies; 
2. Modify the code when `tigris_use_cache == FALSE` to get that to work for you as well.

**Comment by walkerke** [comment]
I've made some changes to address this in https://github.com/walkerke/tigris/commit/333a63c28f74d8fc6dd18869cf98e8dd65952027.  Please install from GitHub and let me know if you are still experiencing issues.

**Comment by walkerke** [comment]
I'm removing curl from the package dependencies as it is causing namespace conflicts.  tigris does not use curl directly, but rather through httr, which it imports; httr should pick up the curl dependency.  I'm wondering if it is something specific to your installation as I notice this issue here: https://github.com/juliasilge/tidytext/issues/69.

**Comment by wujianzhao** [comment]
error：Download failed; check your internet connection or the status of the Census Bureau website
                 at http://www2.census.gov/geo/tiger/.
