### ISSUE TITLE
Add core_based_statistical_areas for 2010

### ISSUE THREAD

**Issue by RoyalTS** [walkerke/tigris#41]
How difficult would it be to add this year? Need it since that's when the last decennial Census was done.

**Comment by walkerke** [comment]
Wouldn't be too tough.  I'll put it on the roadmap.

**Comment by RoyalTS** [comment]
Anything I can do to help?

**Comment by walkerke** [comment]
Thanks for the offer!  Honestly, it shouldn't take me too long at all.  I'm planning to work on issues for my packages this week, so I should be able to get it done pretty soon.

**Comment by gmellon** [comment]
Hello - have the package edits you've been working on this week affected the functionality of the "core_based_statistical_areas" function? I'm trying to download the 2016 shapefiles, which have been working great for months, but then I got this error message today: 

downloaded 0 bytes
Error in download.file(url, tiger_file, mode = "wb") : 
  cannot download all files
In addition: Warning message:
In download.file(url, tiger_file, mode = "wb") :
  URL 'http://www2.census.gov/geo/tiger/TIGER2016/CBSA/tl_2016_us_cbsa.zip': status was 'Couldn't connect to server'

**Comment by walkerke** [comment]
This functionality is now added as of https://github.com/walkerke/tigris/commit/deddeb2b5d5374b647703c836baf849133586a55.
