### ISSUE TITLE
Download fails in Win10 R 3.4.1

### ISSUE THREAD

**Issue by leehach** [walkerke/tigris#43]
I just installed R 3.4.1 and tigris 0.5.3 on Windows 10. When I try to run any download functions (`states()`, `counties()`) I get an error that the URL cannot be opened. For example

    > spdfCounty = counties(state = "NY", refresh = TRUE)
    trying URL 'http://www2.census.gov/geo/tiger/TIGER2015/COUNTY/tl_2015_us_county.zip'
    Error in download.file(url, tiger_file, mode = "wb") : 
      cannot open URL 'http://www2.census.gov/geo/tiger/TIGER2015/COUNTY/tl_2015_us_county.zip'
    In addition: Warning message:
    In download.file(url, tiger_file, mode = "wb") :
      InternetOpenUrl failed: 'A redirect request will change a non-secure to a secure connection'

This had been working for me in R 3.3.1 (but a few months ago, just upgraded the version on this computer). It is also working on a Linux computer (R 3.4.1, tigris 0.5.3).

FWIW, I've confirmed that the URL works in a browser. I've tried calling `download.file` directly, and that fails. However, if I change the URL to `ftp://ftp.census.gov/...` that works!

**Comment by leehach** [comment]
After additional testing, the issue appears beginning with tigris 0.5.1. Version 0.5 works fine in both R 3.3.3 and 3.4.1. Version 0.5.1 fails (error as above) in both R 3.3.3 and 3.4.1.

Also, httr is version 1.2.1 in all cases. I initially thought that might be the problem (isn't that the package that is responsible for downloading?), but there was no difference in httr version between the failing/passing environment.

Again, this is on Win10. I have not tested on other Win versions, but I have tested on Linux and the issue does not manifest.

**Comment by walkerke** [comment]
Can you try installing the dev version from GitHub and seeing if that fixes it?  If not I have a hunch that my next update will do it.  Also- it runs without error on Windows 8, so I think it is specific to Windows 10.

**Comment by leehach** [comment]
As I am preparing for a workshop using this package, I don't want to mess around with dev version right now. I will try to test next week. Sorry for the delay, and thank you for your response.

**Comment by walkerke** [comment]
Sounds good.  One thing you might try with 0.5.3 is setting `options(tigris_use_cache = TRUE)` which is the default behavior in 0.5, but not in versions 0.5.1 and later.  If 0.5 is working for you, I'd guess this would get 0.5.3 to work for you as well in the meantime.  

Version 0.6 should be off to CRAN in the next week or so, which I think will fix this issue.

**Comment by leehach** [comment]
`options(tigris_use_cache = TRUE)` did not fix it. I think I tried that when I was testing, but I just tried again anyway and confirmed that the issue remains.

**Comment by walkerke** [comment]
Are you still having issues?  I've tested tigris version 0.5.3 on Windows 10 and run the package without problems.

**Comment by walkerke** [comment]
I haven't heard anything new about this, so I'm going to go ahead and close this issue.
