### ISSUE TITLE
congressional_districts 114 - url not found

### ISSUE THREAD

**Issue by shannonk** [walkerke/tigris#44]
Census seems to have moved the files referenced in the package so that when one tries to use the "congressional_districts" function, the following error message is returned:
> co_cd <- congressional_districts("Colorado", cb = TRUE, resolution = '20m')
trying URL 'http://www2.census.gov/geo/tiger/GENZColorado/shp/cb_Colorado_us_cd114_20m.zip'
Error in download.file(url, tiger_file, mode = "wb") : 
  cannot open URL 'http://www2.census.gov/geo/tiger/GENZColorado/shp/cb_Colorado_us_cd114_20m.zip'
In addition: Warning message:
In download.file(url, tiger_file, mode = "wb") :
  cannot open URL 'http://www2.census.gov/geo/tiger/GENZColorado/shp/cb_Colorado_us_cd114_20m.zip': HTTP status was '404 Not Found'

**Comment by walkerke** [comment]
Congressional districts are only available for the whole country, so you'll need to first grab all the districts and then subset for Colorado.  This will work: 

```r
library(tigris)

cd <- congressional_districts(cb = TRUE, resolution = "20m")

co_cd <- cd[cd$STATEFP == "08", ]
```

**Comment by walkerke** [comment]
That said - I've just pushed an update that allows you to get the new 115th congress dataset.  Just set `year = 2016` in the function call to do this.

**Comment by shannonk** [comment]
Great!:)
