### ISSUE TITLE
Installing tigris without sf

### ISSUE THREAD

**Issue by aakbarie** [walkerke/tigris#46]
HI, I work in an environment where we can't get rgdal 2.0+ version on our servers. Is there a way to install tigris without the sf package which only works with rgdal 2.0+?

**Comment by walkerke** [comment]
I added sf support at 0.5; the previous CRAN version was 0.3.3.  So you could install the old version:  

```r
library(devtools)
install_version("tigris", version = "0.3.3", repos = "http://cran.us.r-project.org")
```
