### ISSUE TITLE
How to set cache dir?

### ISSUE THREAD

**Issue by RoyalTS** [walkerke/tigris#47]
Maybe I'm just a little dense but I've been looking at the docs for ~10 minutes now and come up empty. Can I somehow set the cache directory?

**Comment by walkerke** [comment]
At the moment, this is not possible.  We use the __rappdirs__ package to determine the appropriate cache directory based on the user's OS: https://github.com/r-lib/rappdirs.  

If you'd like this feature, I'd be willing to consider it as a feature request.

**Comment by RoyalTS** [comment]
The reason I'm asking about this is that tigris dumps the zip files it downloads into the directory in which the script that's being run resides. If I understand rappdirs correctly that shouldn't happen, right?

**Comment by walkerke** [comment]
No it shouldn’t happen.  What version of tigris are you on and what OS are you using?  Also does `getOption(“tigris_use_cache”) return `TRUE`?

**Comment by RoyalTS** [comment]
Ah, I think I may know what might be happening. I'm calling `tigris::places(state = 'CA', year = 2015, class = 'sf')`, i.e. calling the function without loading the package. And if the package isn't loaded the `tigris_use_cache` option isn't set?

**Comment by gregmacfarlane** [comment]
+1 for manually specifying an alternative cache directory. I'm building a server-side application that I'd like to draw files from if we've downloaded them before. Also, confirms that cache location is the local folder if you call `tigris::places`

**Comment by walkerke** [comment]
Yes I think I'll look to include this feature in the next version of the package.

**Comment by walkerke** [comment]
I've just pushed this functionality in https://github.com/walkerke/tigris/commit/b17ad176a9566b7e7514e422d9f267881dda57a2.  It works using a new function, `tigris_cache_dir()`, like this: 

`tigris_cache_dir("PATH TO YOUR NEW CACHE DIRECTORY")`

This function writes your specified cache directory to your .Renviron so you only have to do this once.  

It is working on my end; @RoyalTS @gregmacfarlane would you mind trying it out when you get a minute?

**Comment by andrew-caudillo** [comment]
I am seeing a similar issue. Trying to run states() fails with an error stating that R cannot access my temp folder. So I created my own directory. tigris_cache_dir() says it was set, but when I restart R, the cache directory is overwritten with the R temp folder again. Any suggestions?
