### ISSUE TITLE
Feature Request? Downloading individual blocks or blockgroups

### ISSUE THREAD

**Issue by willbmisled** [walkerke/tigris#49]
Hi, your package is really useful.  I've been using it to download census blocks by county and state.  Often, however, I need only a few blocks and downloading an entire county can be time consuming.  Is there a way to download specific blocks or block groups instead.  Thanks so much.

**Comment by walkerke** [comment]
I'm glad you've found the package useful!  This is a limitation of how the data are provided by the Census Bureau.  Block shapefiles are available by state; tigris downloads the state shapefile then subsets by county in R.  As such there isn't a way to speed up the download outside of a faster internet connection.  However, I'd recommend: 

* Using caching with `options(tigris_use_cache = TRUE)`; 
* Using the simple features class with `class = "sf"` or `options(tigris_class = "sf")`; this speeds loading times signficantly (especially when paired with shapefile caching); 
* Identifying the blocks - or region of potential blocks - you need and saving out as a .rds file, then loading back in as needed.

**Comment by willbmisled** [comment]
Hi Kyle: thanks for getting back to me on this.  I am already use the cache
and will add the SF option.  For the final suggestion if you save the
downloaded data to .rds and  reload to memory will [tigris] find it?

Thanks again for you help.l  Cheers. Bryan.
