### ISSUE TITLE
'roads' function fails to download specific county.

### ISSUE THREAD

**Issue by rsmiller74** [walkerke/tigris#50]
I am using your package to calculate county road density for every U.S. county.  I have processed 2328 counties but the function breaks on one specific county in South Dakota. South Dakota counties before and after appear to work.  Code and session info below.

Great package! 

> st.val="South Dakota"
> fips.val="113"
> 
> #Read Roads for state and county
> in.roads <- roads( st.val, fips.val, year=2015)
Using FIPS code '46' for state 'South Dakota'
Previous download failed.  Re-download attempt 1 of 3...
Downloading: 150 kB     
Previous download failed.  Re-download attempt 2 of 3...
Downloading: 150 kB     
Previous download failed.  Re-download attempt 3 of 3...
Downloading: 150 kB     
Error: Download failed; check your internet connection or the status of the Census Bureau website
                 at http://www2.census.gov/geo/tiger/.

> sessionInfo(package="tigris")
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1
attached base packages:
character(0)
other attached packages:
[1] tigris_0.5.3

**Comment by walkerke** [comment]
I'm glad you've found the package useful!  Your issue is that county 113 - Shannon County, SD - doesn't exist anymore.  The county has been renamed Oglala Lakota County (https://en.wikipedia.org/wiki/Oglala_Lakota_County,_South_Dakota) and now has a FIPS code of 102.
