### ISSUE TITLE
Problems Working With tmap

### ISSUE THREAD

**Issue by jrisi256** [walkerke/tigris#52]
I just wanted to start off by saying thank you for creating this package! It's so incredibly useful!
I also raised this issue on the tmap Github page here: https://github.com/mtennekes/tmap/issues/165.

I'll start from the beginning. I want to create my own interactive maps of the United States using data I've obtained from various sources. After searching around, tmap seemed like a good solution for me. After poking around for some tutorials, I found this one for creating interactive choropleths: https://github.com/mtennekes/tmap/blob/master/demo/USChoropleth/US_choropleth.R.

The demo worked! I now wanted to add tigris to my workflow. So I created the following R script which pretty much follows the above demo code with only slight changes adding in tigris:

```
library(readxl)
library(grid)
library(tmap)
library(tmaptools)
library(tigris)
#options(tigris_class = "sf")

# function to obtain Food Environment Atlas data (2014)
get_food_envir_data <- function() {
  dir <- tempdir()
  download.file("https://www.ers.usda.gov/webdocs/DataFiles/48731/February2014.xls?v=41688", destfile = file.path(dir, "DataDownload.xls"), mode="wb")
  read_excel(file.path(dir, "DataDownload.xls"), sheet = "HEALTH")
}

# obtain Food Environment Atlas data
FEA <- get_food_envir_data()

# obtain US county shape
US_c <- counties()

# create FIPS variable
US_c$FIPS <- paste0(US_c$STATEFP, US_c$COUNTYFP)

# append data to shape
US_c <- append_data(US_c, FEA, key.shp = "FIPS", key.data = "FIPS", ignore.duplicates = TRUE)

# interactive choropleth
ttm()
qtm(US_c, fill = "PCT_OBESE_ADULTS10")
```
However, this causes my RStudio application to crash. The reason being my RAM is totally overloaded as R quickly uses up all of 8 GB of RAM.

I tried to figure out why it was when I used tigris I was crashing R. I quickly found out that the shape files obtained in the tmap demo were nearly 10x smaller than the shape files obtained through tigris. Yet, when you draw a static map using the two different shape files, the maps of the U.S. counties seem to be the same!

So my question is, am I doing something wrong when I call the U.S. counties? Why are my shape files so big? Any help would be greatly appreciated.

**Comment by jrisi256** [comment]
Well I think I solved the issue. You need to set cb=TRUE and adjust the resolution to an appropriate resolution so the size isn't too big.

**Comment by walkerke** [comment]
Yes, that's how to do it!  For others who view this in the future: 

```r
US_c <- counties(cb = TRUE, resolution = "20m")
```
