### ISSUE TITLE
tilde expansion for cache directory

### ISSUE THREAD

**Issue by tarakc02** [walkerke/tigris#54]
On Windows (with `options(tigris_use_cache = TRUE)`) , this gives me an error:

```
Sys.setenv(TIGRIS_CACHE_DIR = "~/.tigris_cache")
ca_districts <- school_districts(state = "06")
```
```
Error in ogrInfo(dsn = dsn, layer = layer, encoding = encoding, use_iconv = use_iconv,  : 
  Cannot open data source
```

But this works fine:
```
Sys.setenv(TIGRIS_CACHE_DIR = path.expand("~/.tigris_cache"))
ca_districts <- school_districts(state = "06")
```

It looks like this happens because `rgdal::readOGR` does not expand the path (so I can recreate the same errors by trying `readOGR("~/.tigris_cache", "tl_2016_06_unsd")`). The problem only occurs when importing to class `sp`, so this works fine:

```
Sys.setenv(TIGRIS_CACHE_DIR = "~/.tigris_cache")
ca_districts <- school_districts(state = "06", class = "sf")
```

**Comment by walkerke** [comment]
Thanks for filing the issue!  I’ll get this corrected.

**Comment by jeffrosenblum** [comment]
Hi, 
I tried a simple 

'> shapefile <- zctas(starts_with = "02")`
and got `Error in !cache : invalid argument type`

it seems to be working if I use:
Sys.setenv(TIGRIS_CACHE_DIR = path.expand("~/.tigris_cache"))
options(tigris_use_cache = TRUE)
shapefile <- zctas(starts_with = "02")

just thought i'd pass that info on.

**Comment by walkerke** [comment]
Both of these errors should now be corrected.  Thank you!
