### ISSUE TITLE
area_water fails for valid state and "county" FIPS code

### ISSUE THREAD

**Issue by CraigMohn** [walkerke/tigris#56]
t <- area_water("VA","515")

Throws an error.   FIPS code "515" is for "Bedford City", which is returned by list_counties("VA").  All other VA counties returned by list_counties work.

**Comment by walkerke** [comment]
Bedford is no longer an independent city in Virginia and is incorporated into Bedford County as of 2013.  See here: http://www.newsadvance.com/news/local/bedford-reversion-to-town-becomes-official-today/article_5dcbc886-e1e9-11e2-a412-001a4bcf6878.html.  

This means that 

```r
bfordcity_water_2013 <- area_water("VA", "515", year = 2013)
```

works, but will fail for later years as the water features are now within Bedford County (FIPS code 019).
