### ISSUE TITLE
Bug: argument `class = 'sf'` does not consistently return sf object

### ISSUE THREAD

**Issue by jlegewie** [walkerke/tigris#57]
Great package! I noticed that tigris does not consistently return sf objects when I use the `class = 'sf'` option. I think it happens when I use a vector of three digit FIPS codes for the `county` argument. Here is an easy way to reproduce the problem:

```
test1 <- tigris::blocks(state = "36", county = c("061", "047"), year = 2010, class = "sf")
class(test1)
# ERROR: test1 is class `SpatialPolygonsDataFrame` and not `sf`
test2 <- tigris::blocks(state = "36", county = "061", year = 2010, class = "sf")
class(test2)
## test2 is class `sf` so it works well here
```

**Comment by walkerke** [comment]
This is now fixed in https://github.com/walkerke/tigris/commit/5f5002cd582eeeea6afb0d7f3f4b0d1eef82e6db.
