### ISSUE TITLE
Bug: `tigris::blocks` fails with default year and vector of county codes

### ISSUE THREAD

**Issue by jlegewie** [walkerke/tigris#58]
Great package! Here is a bug
```
tigris::blocks(state = "36", county = c("061", "047"))
# Error in if (length(county) > 1 && year < 2011) { : 
#  missing value where TRUE/FALSE needed
```

It works when I change `year` to 2010.

**Comment by walkerke** [comment]
I think I know what is going on with both of your filed issues.  Block data are available from the Census website by county for 2010, but only by state for 2011 - in which tigris does the subsetting from within R.  There is likely some logic in there that needs to be cleaned up.

**Comment by walkerke** [comment]
I've fixed this bug in https://github.com/walkerke/tigris/commit/ca133ac3644824eac8329471c83b3886aad58c85.
