### ISSUE TITLE
Feature request: shift_geo for tigris datasets

### ISSUE THREAD

**Issue by walkerke** [walkerke/tigris#62]
On Twitter: 

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/kyle_e_walker?ref_src=twsrc%5Etfw">@kyle_e_walker</a> Sooo, is shift_geo going to be added to tigris functions like state() any time soon? :)</p>&mdash; Andrew Ba Tran (@abtran) <a href="https://twitter.com/abtran/status/1019954105584967686?ref_src=twsrc%5Etfw">July 19, 2018</a></blockquote>

**Comment by walkerke** [comment]
I opted against this a year ago due to the existence of the albersusa package: https://github.com/walkerke/tigris/issues/33.  However it might be a good idea to re-consider especially for the purpose of historic shapefiles and non-state and county datasets that have national coverage.  

The key question: should this be a _parameter_ in the functions, or a special _function_ itself to transform the datasets?

**Comment by gergness** [comment]
Something like a `coord_albersusa()` that adapts `coord_sf()` seems really natural to me, but when I tried to work on this I didn't get very far. (I'm also not sure about performance implications for things like facets & gganimate)

**Comment by walkerke** [comment]
Good point @gergness.  I'd like to experiment with some sf-based solutions to accomplish this as speed will be a priority for moving things around.  One thing about the tigris datasets as well is that they include state and county equivalents like Puerto Rico, Guam, etc.  As such it'll be important to consider what to do with these areas (e.g. where Puerto Rico should go).

**Comment by gergness** [comment]
Sounds good, looking forward to seeing what you come up with!

**Comment by walkerke** [comment]
Closing as this project is on-going at https://github.com/uncoast-unconf/ggcart.
