### ISSUE TITLE
Question About Obtaining Shapefiles From Older Years

### ISSUE THREAD

**Issue by jrisi256** [walkerke/tigris#66]
Hi! Great package! Thanks so much for making it.

Quick question specifically about the school districts shape-files.

It says here you can only get them going back as far as 2011 using the tigris package. How would I check to see if there are shapefiles which do in fact go back further in time?

And then another quick question (if you don't mind), is there a general rule of thumb of what to do when mapping data before there are any shapefiles available? For example, the Small Area Income and Poverty Estimates program (SAIPE) has poverty measures by school district going back to 1995. Assuming the Census Bureau doesn't have shape files for school districts going back that far, what would one do?

Sorry if these questions are a little too off-topic!

**Comment by walkerke** [comment]
All Census shapefiles are available at https://www2.census.gov/geo/tiger/; if I don't support it in tigris, you may find it there.  For the second question - I'm not really sure.  Perhaps you could go to specific state departments of education who may have historic files?
