### ISSUE TITLE
county_subdivision function not working for Massachusetts with cb = TRUE

### ISSUE THREAD

**Issue by jpkennedy144** [walkerke/tigris#68]
> x = county_subdivisions("Massachusetts", cb = TRUE)
Using FIPS code '25' for state 'Massachusetts'
Error in ogrInfo(dsn = dsn, layer = layer, encoding = encoding, use_iconv = use_iconv,  : 
  Cannot open layer
In addition: Warning message:
In unzip(file_loc, exdir = tmp) : error 1 in extracting from zip file

**Comment by walkerke** [comment]
I can't reproduce this.  Are you able to get other datasets?  Are there internet connectivity issues?

**Comment by jpkennedy144** [comment]
Issue seems fixed. Perhaps it was just a temporary glitch from upstream. I'll close the issue.
