### ISSUE TITLE
R tigris issues with 1990 and 2010 but not 2000

### ISSUE THREAD

**Issue by billinsb** [walkerke/tigris#69]
I am inconsistently getting the following error when running this code. It is perplexing since it works for some years but not others and sometimes works fine for a couple states and then does not work again. I have played with tigris_use_cache too. Any help is appreciated. 

tracts2000 <- tracts(state.id[[i]], county = NULL, cb = TRUE, year = 2000, refresh = TRUE)
tracts1990 <- tracts(state.id[[i]], county = NULL, cb = TRUE, year = 1990, refresh = TRUE)
tracts2010 <- tracts(state.id[[i]], county = NULL, cb = TRUE, year = 2010, refresh = TRUE)
        

Using FIPS code '24' for state 'MD'
  |==============================================================================| 100%

Using FIPS code '24' for state 'MD'
  |==============================================================================| 100%
Error in ogrInfo(dsn = dsn, layer = layer, encoding = encoding, use_iconv = use_iconv,  : 
  Cannot open layer
In addition: Warning message:
In unzip(file_loc, exdir = tmp) : error 1 in extracting from zip file

Using FIPS code '24' for state 'MD'
  |==============================================================================| 100%
Error in ogrInfo(dsn = dsn, layer = layer, encoding = encoding, use_iconv = use_iconv,  : 
  Cannot open layer
In addition: Warning message:
In unzip(file_loc, exdir = tmp) : error 1 in extracting from zip file

**Comment by walkerke** [comment]
I can't reproduce this - though what I'm seeing is often associated with an internet connectivity issue.  Is this still a problem?

**Comment by billinsb** [comment]
Hey kyle,

It is not consistent issue but frequent enough to keep crashing my programs that loop through states and years. I am surprised internet connectivity would drive differences across years.

I will let you know if I figure out what is causing this to happen. Any other thoughts would be great. It seems to download but not able to open/find the shapefiles. I played with the cache option directory a fair amount and doesn't change the outcome.

Steve

On Oct 12, 2018 11:40 AM, Kyle Walker <notifications@github.com> wrote:

I can't reproduce this - though what I'm seeing is often associated with an internet connectivity issue. Is this still a problem?

**Comment by walkerke** [comment]
I just ran the following without issue: 

```r
library(tigris)
library(tidyverse)
options(tigris_use_cache = TRUE, tigris_class = "sf")

state_codes <- c(state.abb, "DC")

tracts1990 <- map(state_codes, ~{
  tracts(state = .x, cb = TRUE, year = 1990)
}) %>%
  rbind_tigris()
```

My guess is that you are having an issue with a corrupted cache; __tigris__ should take care of this internally but it doesn't seem like that is happening.  I'd recommend navigating to your cache directory; folders that exist there, but are empty, are the result of a bad download.  Delete the corrupted folders and try again for the states that are failing with caching enabled.  If all the data are in the cache directory correctly, you should be able to use `options(tigris_use_cache = TRUE)` and read from your cache directory from there on out, avoiding those issues moving forward.

**Comment by billinsb** [comment]
Thanks for the thoughts. That sounds promising. I will try your suggestion and let you know if I have any more problems.

Thanks so much!!

Steve

On Oct 12, 2018 3:34 PM, Kyle Walker <notifications@github.com> wrote:

I just ran the following without issue:

library(tigris)
library(tidyverse)
options(tigris_use_cache = TRUE, tigris_class = "sf")

state_codes <- c(state.abb, "DC")

tracts1990 <- map(state_codes, ~{
  tracts(state = .x, cb = TRUE, year = 1990)
}) %>%
  rbind_tigris()

My guess is that you are having an issue with a corrupted cache; tigris should take care of this internally but it doesn't seem like that is happening. I'd recommend navigating to your cache directory; folders that exist there, but are empty, are the result of a bad download. Delete the corrupted folders and try again for the states that are failing with caching enabled. If all the data are in the cache directory correctly, you should be able to use options(tigris_use_cache = TRUE) and read from your cache directory from there on out, avoiding those issues moving forward.

**Comment by walkerke** [comment]
@billinsb I've been experiencing similar issues to you this morning on my EC2 instance running R, but not on my Windows machine.  Certain datasets are returning 503 (service unavailable) errors, but it is not consistent across datasets and across states, as you describe.  

I'm going to investigate this further.  By the way - what is your R and operating system setup?

**Comment by billinsb** [comment]
Thanks Kyle,

I was getting it to work the last couple days by playing the cache option and erasing bad files when they downloaded but this morning it is not working again for me either.

I am using R 3.5.1 for windows (64 bit) on a Windows Server Standard 2016 operating system.

Steve

**Comment by walkerke** [comment]
@billinsb I've been in touch with Census all morning about this - it is working again for me but I'll still investigate.  As you are on Windows Server I wonder if the issue is with server-based R versions, but I'm not sure.  I'll let you know what I learn.
