### ISSUE TITLE
zctas(..., year = 2010, state = 'NJ') returns ZCTAs for entire US

### ISSUE THREAD

**Issue by everetr** [walkerke/tigris#71]
I want to make a map of all ZTCAs associated with New Jersey, only. I'm running the following:
```
library(sf)
library(tigris)
library(tmap)

options(tigris_class = 'sf')
options(tigris_use_cache = T)

# `?zctas` documentation says state selection only available for 2000 or 2010.
nj_zips = tigris::zctas(cb = T, year = 2010, state = 'NJ')

tmap_mode('plot')

p = nj_zips %>%
  tm_shape() +
  tm_borders(col = 'black')

p
 ```
I expect to see a map that sorta looks like NJ. Instead, I get a map of every ZCTA in the US, which I can only view in RStudio after waiting quite a while. Here is the shapefile that was cached, in QGIS:

![image](https://user-images.githubusercontent.com/9023041/50727278-ae0b2800-10e6-11e9-9f10-179bae001e99.png)

However, when I instead set `year = 2000`, I get the 2000 shapefile for New Jersey. 

![image](https://user-images.githubusercontent.com/9023041/50727339-92ece800-10e7-11e9-9a38-39fa2ab3050a.png)

Is this a bug, am I doing something wrong, or does this mean that a 2010 ZTCA shapefile isn't available for NJ at all? Thank you for your time, and thank you very much for this package.

Edit: I should amend my question. I know I can get ZTCAs for NJ only using the US ZTCA shapefile via some sf/tmap functions. What I mean to ask is, is there no way to download a 2010 shapefile of ZTCAs for NJ only via tigris::ztcas()? 

# Environment

I'm using Ubuntu 18.04.1. RStudio v1.1.463. R 3.5.2. tigris 0.7. tmap 2.1-1. sf 0.7-2. GEOS 3.7.0, GDAL 2.3.2, PROJ 5.2.0.

**Comment by lschomp** [comment]
same problem for "pa" this works, when specifying 2000. 
pa <- zctas(cb = TRUE, year=2000, state= "PA")

**Comment by walkerke** [comment]
The US Census Bureau no longer releases ZCTA shapefiles by state, as ZCTAs do not map neatly to state boundaries (there are several that cross state lines).  As such right now for years after 2000 you'd need to do spatial subsetting.  

That said - I am working on a potential solution right now with lookup tables that I hope to have available in the next release.

**Comment by lschomp** [comment]
Oh, that makes sense. Thank you so much!

**Comment by lschomp** [comment]
Hi there, is there any update on this? 

I am trying to get a list of zctas for the 49 states (can't set state != to HI, AK, etc).  

I am wondering if I can modify the below code from the R journal article, and use the GEOID from the States shapefile to pull only ZCTAs where the first two digits of the GEOID10 is found in the states GEOID list? Will that work to get a ZCTAs file subset? 

Thank you!  I am really enjoying Tigris.
Lori 

***

us_states <- unique(fips_codes$state)[1:51]
continental_states <- us_states[!us_states %in% c("AK", "HI")]
us_pumas <- rbind_tigris(
  lapply(
    continental_states, function(x) {
      pumas(state = x, cb = TRUE)
    }
) )
plot(us_pumas)
