### ISSUE TITLE
R Error downloading shapefiles using Tigris

### ISSUE THREAD

**Issue by irinasm** [walkerke/tigris#72]
```
library(tigris)
options(tigris_use_cache = FALSE) 
geoc <- counties(cb=TRUE)
```

I get the following error:

```
Error in ogrInfo(dsn = dsn, layer = layer, encoding = encoding, use_iconv = use_iconv,  : 
  Cannot open data source
In addition: Warning message:
In unzip(file_loc, exdir = tmp) : error 1 in extracting from zip file
```

I would appreciate your help! If rolling back to  the older version of Tigris might help, please let me know how to install the older version. Thank you!

**Comment by irinasm** [comment]
I ununstalled tigris, and then reinstalled development version from github. That got rid of the error "Error in ogrInfo(dsn = dsn..."

However I now have the error:

> > us_geoc <- counties(cb=TRUE)
> Previous download failed.  Re-download attempt 1 of 3...
> Previous download failed.  Re-download attempt 2 of 3...
> Previous download failed.  Re-download attempt 3 of 3...
> Error: Download failed; check your internet connection or the status of the Census Bureau website
>                  at http://www2.census.gov/geo/tiger/.

Even though census website is up, and my internet is also up. What should I do? I am doing this from work, but I had no problem downloading the package from github, and the Rstudio is set to use internet explorer proxy settings.

**Comment by irinasm** [comment]
Sorry for confusion, but I have tried to reinstall the Tigris again, and I unchecked and rechecked the option to use IE proxy. .Now I am back to having the first error: 

"Error in ogrInfo(dsn = dsn, layer = layer, encoding = encoding, use_iconv = use_iconv,  : 
  Cannot open data source".  

I can also no longer download the package from github either.

**Comment by walkerke** [comment]
Are you using a server version of R?  This problem can arise when Census blocks connections to its website intermittently.

**Comment by irinasm** [comment]
Hi, thank you. I am using R at work, but as far as I can tell it is not a server version. It is a local installation. If you could tell me how to double check on this, I will do.

At this point, after spending all night to fix this, I have new issues, that likely have to do with curl/httpr packages: I have tried to reinstall these to refresh my connection, but that probably did not go through  not completely. No I have "host name not resolved" when I try to re-download tigris from github (I was able to do this earlier, before my second post above. I am now going to try to have both r and rstudio completely reinstalled to get out of this new problem (unless you have another suggestion).

Thank you for your help!

**Comment by irinasm** [comment]
Incidentally, at the time when I was getting "Previous download failed. Re-download attempt 1 of 3..." on my work machine, I tried to do this on my personal laptop, and there I did not get this error. That led me to believe that it was a proxy setting issue on my work computer, and I tied to refresh the proxy settings, curl and httr. As a result of that I now can not even download tigris from github. I am now getting R and Rstudio completely removed and reinstalled.

**Comment by walkerke** [comment]
I've heard of issues with work firewalls blocking data downloads using tigris before (see https://github.com/walkerke/tigris/issues/60).  I haven't yet solved this issue as I suspect it'll involve a substantial internal refactor.  Let me know if it ends up working on your work computer, however.

**Comment by irinasm** [comment]
The twitter link that that is in that post does not work, so I do not know what problem that was exactly. Was it also "Previous download failed. Re-download attempt 1 of 3..." type of problem?

I can request exception for connections that are blocked, but I need to know exactly what is in the way. I still have not solved the issue that arose after I messed up proxy settings (resolving host). But back when I was gettting  "Previous download failed. Re-download attempt 1 of 3..." my host was resolving through R. Also, through browser I ca download those files manually. So I doubt that was the firewall issue.

**Comment by irinasm** [comment]
I have had both R and Rstudio completely reinstalled, and I also removed all the old libraries. However still, I get this:

> > devtools::install_github('walkerke/tigris')
> Error in curl::curl_fetch_memory(url, handle = h) : 
>   Could not resolve host: api.github.com

I was able to do this last night, before I created and then deleted renviron file with proxi settings. I do not know how to get back to that point when I was able to successfully download tigris through github...

**Comment by irinasm** [comment]
I opened another ticket with the issue I am now having with downloadig tigris from github:

https://github.com/r-lib/devtools/issues/1996 

While I try to resolve this issue, can you let me know if there is a workaround, because I need to work on this somewhat urgently. Since I can successfully download these shapefiles to my home computer, is there a way to copy them over from one computer to another? If so, where are they and how would I copy them?

Thank you!

**Comment by walkerke** [comment]
You can download all the Census shapefiles from https://www2.census.gov/geo/tiger/; that's where tigris pulls from.  If you want to use them with tigris, look for your tigris cache directory (`rappdirs::user_cache_dir("tigris")`) and upload them there, then set `options(tigris_use_cache = TRUE)` and you'll be able to use them.
