### ISSUE TITLE
Copying shape files from one computer to another

### ISSUE THREAD

**Issue by irinasm** [walkerke/tigris#74]
I am having a problem downloading Tigris from github, and it looks like a hard problem to solve. It worked for me yesterday, before I tried to do some minor changes to proxy setting (which I rolled back). I have completely reinstalled R three times since then, and nothing helps.

Is there a work around? I urgently need to use these files, and I am stuck. I am able to download shapefiles from my home computer. Can I zip them and copy over to my work computer? If so, how? Where do I copy  them to?

Thank you!

**Comment by walkerke** [comment]
If the Census Bureau website is having a server hiccup - which does happen - all files used by tigris are available at https://www2.census.gov/geo/tiger/ for manual download.  You can read them into R like any other spatial object with `sf::read_sf()` or `sf::st_read()`.  If you want to use them with tigris, look for your cache directory with `rappdirs::user_cache_dir("tigris")` and unzip the folders there.
