### ISSUE TITLE
No 2018 CD's?

### ISSUE THREAD

**Issue by hnhd** [walkerke/tigris#75]
Just noticed there was no 2018 CD shapefiles available. 

I imagine this is just due to neglect to pull the most recent shapefiles. Shouldn't be hard to write a script that pulls the most recent version of all the shapefiles that is just refreshed for every new year shapefile release, no?

Big fan of the tigris package and would hate to have to replace it with manual pulls.

**Comment by bschneidr** [comment]
What's a CD? Congressional District?

If that's what you're asking about, you can install the development version to get shapefiles for the 116th congress.

```
devtools::install_github("walkerke/tigris")
library(tigris)
congressional_districts(year = 2018)
```

The current version on CRAN isn't yet updated to include the Congress shapefiles for 2018.

**Comment by walkerke** [comment]
Thanks @bschneidr!  That is correct - and yes I need to get a new version up on CRAN.
