### ISSUE TITLE
tigris installation problem

### ISSUE THREAD

**Issue by iracohen44** [walkerke/tigris#77]
When I tried installing tigris I got the following error:

> library(tigris)
Error: package or namespace load failed for ‘tigris’:
 .onLoad failed in loadNamespace() for 'sf', details:
  call: get(genname, envir = envir)
  error: object 'group_map' not found
In addition: Warning message:
package ‘tigris’ was built under R version 3.5.3 

I am not proficient enough in R, yet, to resolve this problem and would appreciate any help

**Comment by walkerke** [comment]
Looks like you'll need a dplyr update.  Try `install.packages("dplyr")` and then try re-installing tigris, and see if that works.

**Comment by iracohen44** [comment]
That solved the problem, thank you very much
