### ISSUE TITLE
Issue with School District Tiger/LINE ShapeFiles in 2018

### ISSUE THREAD

**Issue by jrisi256** [walkerke/tigris#78]
I get an error when trying to obtain the latest Tiger/LINE ShapeFiles for 2018 for secondary and elementary school districts. Interestingly, there is no issue with unified school districts. The error is the same for secondary/elementary school districts:

```r
Error in CPL_read_ogr(dsn, layer, query, as.character(options), quiet,  : 
  Opening layer failed.
In addition: Warning message:
In unzip(file_loc, exdir = tmp) : error 1 in extracting from zip file
```

```r
#### Runs fine
sdUnified <- school_districts(state = "34", type = "unified", year = 2017)
sdUnified <- school_districts(state = "34", type = "unified", year = 2018)

#### Also runs fine
sdSecondary <- school_districts(state = "34", type = "secondary", year = 2017)
sdElementary <- school_districts(state = "34", type = "elementary", year = 2017)

#### Does not work
sdSecondary <- school_districts(state = "34", type = "secondary", year = 2018)
sdElementary <- school_districts(state = "34", type = "elementary", year = 2018)
```

**Comment by walkerke** [comment]
@jrisi256 just tested and your code works for me.  Occasionally `httr::GET()` requests from tigris to the Census servers fail.  I looked into it with Census a while back and it would have required combing through server logs to try to isolate the error - and it usually starts working again after a while.  

Not the most satisfactory "solution" but try again as I believe it should work now.  Please re-open if you are having further issues.
