### ISSUE TITLE
Issue opening tracts for certain states

### ISSUE THREAD

**Issue by eturkel** [walkerke/tigris#79]
depa <- rbind_tigris(
  tracts("DE", cb = TRUE), 
  tracts("PA", cb = TRUE)
)

This code throws the following error after DE tracts are downloaded: 

Cannot open layer cb_2016_42_tract_500k
Error in CPL_read_ogr(dsn, layer, query, as.character(options), quiet,  : 
  Opening layer failed.
In addition: Warning message:
In unzip(file_loc, exdir = tmp) : error 1 in extracting from zip file

However, the identical code for other states works fine. 

demd <- rbind_tigris(
  tracts("DE", cb = TRUE), 
  tracts("MD", cb = TRUE)
)

Any ideas are appreciated.

**Comment by walkerke** [comment]
Your code works for me.  What operating system are you on?  Sometimes the Census file server has hiccups which I unfortunately can't predict.  I've seen this happen more frequently with server-based versions of R.  

Moving forward I'd recommend using shapefile caching with `options(tigris_use_cache = TRUE)`; you then won't have to re-download the data and rely on the Census servers.
