### ISSUE TITLE
Trouble downloading Virginia geographies

### ISSUE THREAD

**Issue by bobidou23** [walkerke/tigris#81]
I've been trying to download census block shapefiles for counties in various states. The below has been working for multiple states, but not Virginia. Change class from "sf" to "sp" doesn't work, picking out a single county (one listed under `list_counties("VA")`) doesn't work, nor does using its FIPS code.

```
blocks("VA", county=c("Alexandria", "Arlington", "Fairfax County", "Fairfax city", 
                                  "Falls Church", "Loudoun", "Manassas city", 
                                  "Manassas Park", "Prince William"), class="sf")
```
It's just Virginia. The error is as follows:
```
Cannot open layer tl_2017_51_tabblock10
Error in CPL_read_ogr(dsn, layer, query, as.character(options), quiet,  : 
  Opening layer failed.
In addition: Warning message:
In unzip(file_loc, exdir = tmp) : error 1 in extracting from zip file
```

**Comment by walkerke** [comment]
I ran your code and it worked for me.  I'm thinking you might have encountered a download error; block files are really large and can be susceptible to internet hiccups.  Also check your tigris cache directory (located at `rappdirs::user_cache_dir("tigris")` and see if `tl_2017_51_tabblock10.zip` is in there; you may need to delete it manually if there was a corrupted download.
