### ISSUE TITLE
CSA definitions were updated in 2018

### ISSUE THREAD

**Issue by josiekre** [walkerke/tigris#83]
Anyone know where to locate the Sep 2018 CSA map as a shapefile? https://www2.census.gov/geo/maps/metroarea/us_wall/Sep2018/CSA_WallMap_Sep2018.pdf

There were a couple changes to the CSA definitions that are not in the current version of  `tigris::combined_statistical_areas()`. 

For example, Minneapolis-St. Paul, MN-WI Combined Statistical Area now includes Owatonna Micropolitan Statistical Area (one extra county), and the central CBSA dropped one county (Sibley County) affecting the CSA too.

**Comment by walkerke** [comment]
You can use the `year` argument to change the year if you'd like - up to 2019 TIGER/Line shapefiles are available.  For example, `tigris::combined_statistical_areas(year = 2019)` gets you the updated boundaries: 

![image](https://user-images.githubusercontent.com/4872833/71708836-844c1600-2db9-11ea-9900-659877c0260a.png)

I'll be sending an update to CRAN in the next couple weeks updating the default year to 2018 (to match with the latest available Census tabular datasets) but you can get the new boundaries in this way too.

**Comment by josiekre** [comment]
Thanks @walkerke. Not sure why I did not try that.
