### ISSUE TITLE
US census web site access denied from Brazil

### ISSUE THREAD

**Issue by bnelsonbr** [walkerke/tigris#86]
US census web site access is denied from Brazil, may be why I get this error:

> library(states)
> myStates <- states(cb = TRUE)  # will download a generalized (1:500k) file
Error in ogrInfo(dsn = dsn, layer = layer, encoding = encoding, use_iconv = use_iconv,  : 
  Cannot open data source
In addition: Warning message:
In unzip(file_loc, exdir = tmp) : error 1 in extracting from zip file

**Comment by walkerke** [comment]
If the Census website is blocked I'm not sure of a workaround here.  You might consider using NHGIS instead: https://nhgis.org/.
