### ISSUE TITLE
State/county TIGER boundaries coarseness issue

### ISSUE THREAD

**Issue by jbranham31** [walkerke/tigris#88]
I recently ran the following to then export the shapefile for use in QGIS:

options(tigris_class = "sf")
states.18 <- tigris::states(cb = FALSE, year = 2018)

After exporting, I noticed the state shapefile is _less_ detailed than the 500k state cartographic boundaries (downloaded previously, not through tigris package).  From the tigris::states() download, I filtered just to Michigan and have included it as an example plot.  Any idea what might be causing this issue?

![Michigan_tigris](https://user-images.githubusercontent.com/23388139/75822159-7e4cc400-5d6d-11ea-96d8-9899b5312f3c.png)

**Comment by walkerke** [comment]
Good question - I originally answered this back in 2015: https://github.com/walkerke/tigris/issues/12.  

The file with `cb = FALSE` is more detailed in the _interior_, but less so around the _exterior_ as it is not clipped to the shoreline and in turn includes official water area (three miles off the land).

**Comment by jbranham31** [comment]
Ahh I see.  Thank you for the helpful response!
