### ISSUE TITLE
Tigris roads plotting with large points at some corners

### ISSUE THREAD

**Issue by andrewvanleuven** [walkerke/tigris#89]
Hi Dr. Walker, 

This is going to seem odd, but I can't figure out what is going on. I am making a series of individual maps for municipalities in Ohio. They will eventually have points for every property transaction parcel, but for now I am just plotting the `places()` + `roads()` + `area_water()`, with the latter two being restricted only to municipal boundaries.

When I plot, I get these weird dots at the edges of my map:
![mwe](https://user-images.githubusercontent.com/33671616/77596109-6f22e700-6ed1-11ea-8f05-752f87cbc7e0.png)

I have isolated the problem to my `"rds"` object, but I don't think I'm doing anything out of the ordinary with my code. Do you have any idea if this is a problem with `tigris`? Or maybe it's something wrong with my `sf` code @edzer. Any insight/help you can provide is much appreciated.

Thanks!

***
## Code:

```
# Packages & Options ------------------------------------------------------
library(tidyverse)
library(sf)
library(tigris)
options(tigris_class = "sf")
options(tigris_use_cache = TRUE)

# Load Map Elements -------------------------------------------------------
oh_ctys <- counties("39", cb = T) %>% 
  st_transform(2834)
town <- places(state = "39", cb = T) %>% 
  mutate(city_fips = as.numeric(GEOID),
         name = NAME) %>% 
  select(city_fips,name,geometry) %>% 
  filter(name == "Athens") %>% 
  st_transform(2834)
cnty <- oh_ctys %>%
  filter(st_intersects(x = ., y = town, sparse = FALSE)) %>% 
  pull(NAME)
rds <- st_intersection(roads("39",cnty) %>% st_transform(.,crs = 2834),town)
h2o <- st_intersection(area_water("39",cnty) %>% st_transform(.,crs = 2834),town)

# Plot Map ----------------------------------------------------------------
ggplot() +
  geom_sf(data = town) +
  geom_sf(data = rds) +
  geom_sf(data = h2o, color = "blue", fill = "cyan") +
  theme_void()
```

**Comment by edzer** [comment]
It could be that some of your objects are mixed geometry types (`GEOMETRYCOLECTION`); you could use `st_collection_extract` to select only the polygons.

**Comment by andrewvanleuven** [comment]
Thank you @edzer ... that worked! 
It's odd though, since I have created several such plots in the past, and this has never been a problem.
Either way, thanks for your help.
