### ISSUE TITLE
tigris::tracts(state="ID", cb= TRUE, year=2015) returns "Cannot open layer"

### ISSUE THREAD

**Issue by SimonCoulombe** [walkerke/tigris#90]
Any other year is fine.

This  code used to work about 3 months ago.  Any idea?
thanks for the package!

**Comment by walkerke** [comment]
Sometimes the Census website has blips.  Try again now and see if it works for you (it did for me).  To avoid this in the future use `options(tigris_use_cache = TRUE)` to store shapefiles locally and read from there instead of downloading.

**Comment by SimonCoulombe** [comment]
wow that was quick ! :)

I upgraded to the github version (devtools::install_github('walkerke/tigris') )   and it worked fine.
