### ISSUE TITLE
wrong data url for congressional_districts in 2010, 2011, 2012

### ISSUE THREAD

**Issue by kuriwaki** [walkerke/tigris#92]
Data download for `congressional_district()` for years 2010, 2011, 2012 fails. (It works fine for all years 2013 and onwards.) 

It seems like the URL the function looks for
https://github.com/walkerke/tigris/blob/b32d11ed03e8e167e50aa541fb3ca4c7b492f8dc/R/legislative.R#L72-L75
is not the correct form only in those years. The folders `GENZ2010`, `GENZ2012` under https://www2.census.gov/geo/tiger/
have different file naming structures than the other years. Also, they  don't have 2011 but they do have a 2010, despite the fact that the tigris function will not allow you to enter `year < 2011`. 

Do their data seem comparable to the 2013- files? It would be great to get cb maps pre-2012, because those are before the decennial redistricting and are significantly different from 2012-2020.

Code:

```
library(tigris)

cd_2010 <- congressional_districts(cb = TRUE, year = 2010)
cd_2011 <- congressional_districts(cb = TRUE, year = 2011)
cd_2012 <- congressional_districts(cb = TRUE, year = 2012)

#> Previous download failed.  Re-download attempt 1 of 3...
# >  |===========================================================| 100%
#> Previous download failed.  Re-download attempt 2 of 3...
#>   |===========================================================| 100%
#> Previous download failed.  Re-download attempt 3 of 3...
#>   |===========================================================| 100%
#> Error: Download failed; check your internet connection or the status of the Census Bureau website

cd_2013 <- congressional_districts(cb = TRUE, year = 2013) # works, as do 2014:2019
```

**Comment by walkerke** [comment]
Looks like the cartographic boundary files for 2010 and 2012 (2011 is missing) have inconsistent structure, so I've added an informative error message as to why they are not available.  You can get these files with `cb = FALSE` from the regular TIGER/Line objects, so I've enabled this in the function.
