### ISSUE TITLE
Requesting Congressional District Shape Files prior to 2011 through the Tigris Package in R

### ISSUE THREAD

**Issue by sharifamlani** [walkerke/tigris#95]
I need Congressional shapefiles for the years 1980 - 1900. 

I called the code:
```
districts <- congressional_districts(cb = TRUE, resolution = '20m', year = 1980)
Error: congressional_districts is not currently available for years prior to 2011.  To request this feature, file an issue at https://github.com/walkerke/tigris.

```

As a result, I'm posting here.

Thank you so much for your assistance

**Comment by walkerke** [comment]
Hi @sharifamlani - this data is not available from the Census website so it won't be included in tigris.  However, there is a project from UCLA that appears to have what you need: http://cdmaps.polisci.ucla.edu/.
