### ISSUE TITLE
NY and NM county subdivisions missing for 2019?

### ISSUE THREAD

**Issue by kmcd39** [walkerke/tigris#98]
Thanks so much for library. Reporting issue that county subdivisions for New Mexico and New York seem to be missing for the year 2019.

I.e, I run 
`tigris::county_subdivisions(state = 35, class = "sf", year = 2019)`  or with state = 36 and I get a "not found" error. (They do seem to be there for 2018.) 

I'm aware this might be issue on census bureau's end but fya

**Comment by walkerke** [comment]
This is working for me; sometimes the Census website has blips.  I'd recommend waiting a bit and trying again.
