### ISSUE TITLE
Congressional Districts by State

### ISSUE THREAD

**Issue by parnelli32** [walkerke/tigris#99]
Is there a way to specify the state who's congressional districts I'd like to see?  Right now, when I run the congressional district function, every congressional district in the country is shown.

**Comment by walkerke** [comment]
I just added this option - use `remotes::install_github("walkerke/tigris")` to get it: 

```r
library(tigris)

ca_cds <- congressional_districts(state = "CA", cb = TRUE)
plot(ca_cds$geometry)
```

![image](https://user-images.githubusercontent.com/4872833/89101734-35ef0c00-d3c8-11ea-81fb-fdb1e8039337.png)

**Comment by parnelli32** [comment]
Thanks! this works great.
